import React, { useState, useEffect, useCallback } from 'react';
import { DragDropContext, Droppable, Draggable } from '@hello-pangea/dnd';
import { getPlayers } from '../services/dataService';
import { positionColors, getDraftCapitalInfo, hasInjuryRisk } from '../utils/helpers';

const STORAGE_KEY_1QB = 'dynasty_myboard_1qb';
const STORAGE_KEY_SF = 'dynasty_myboard_sf';

const MyBoard = () => {
  const [activeFormat, setActiveFormat] = useState('oneQB');
  const [board1QB, setBoard1QB] = useState([]);
  const [boardSF, setBoardSF] = useState([]);
  const [allPlayers, setAllPlayers] = useState([]); // eslint-disable-line no-unused-vars
  const [showExport, setShowExport] = useState(false);

  useEffect(() => {
    const loadPlayers = async () => {
      const data = await getPlayers();
      setAllPlayers(data);

      // Load from localStorage or default to rank order
      const saved1QB = localStorage.getItem(STORAGE_KEY_1QB);
      const savedSF = localStorage.getItem(STORAGE_KEY_SF);

      if (saved1QB) {
        const ids = JSON.parse(saved1QB);
        setBoard1QB(ids.map(id => data.find(p => p.id === id)).filter(Boolean));
      } else {
        setBoard1QB([...data].sort((a, b) => a.rank.oneQB - b.rank.oneQB));
      }

      if (savedSF) {
        const ids = JSON.parse(savedSF);
        setBoardSF(ids.map(id => data.find(p => p.id === id)).filter(Boolean));
      } else {
        setBoardSF([...data].sort((a, b) => a.rank.superflex - b.rank.superflex));
      }
    };
    loadPlayers();
  }, []);

  const persist = useCallback((format, board) => {
    const key = format === 'oneQB' ? STORAGE_KEY_1QB : STORAGE_KEY_SF;
    localStorage.setItem(key, JSON.stringify(board.map(p => p.id)));
  }, []);

  const currentBoard = activeFormat === 'oneQB' ? board1QB : boardSF;
  const setCurrentBoard = activeFormat === 'oneQB' ? setBoard1QB : setBoardSF;

  const handleDragEnd = (result) => {
    if (!result.destination) return;
    const items = Array.from(currentBoard);
    const [reordered] = items.splice(result.source.index, 1);
    items.splice(result.destination.index, 0, reordered);

    setCurrentBoard(items);
    persist(activeFormat, items);
  };

  const exportBoard = () => {
    const lines = currentBoard.map((p, i) =>
      `${i + 1}. ${p.name} (${p.position})${p.college ? ` - ${p.college}` : ''}${p.draftRound ? ` | R${p.draftRound} Pick #${p.draftPick} ${p.draftTeam || 'TBD'}` : ''}${hasInjuryRisk(p) ? ' ⚠️ INJURY' : ''}`
    );
    const header = activeFormat === 'oneQB' ? '=== MY 1QB ROOKIE BOARD ===' : '=== MY SUPERFLEX ROOKIE BOARD ===';
    return `${header}\n${'='.repeat(header.length)}\n${lines.join('\n')}\n\nGenerated by Dynasty Rookie Scout`;
  };

  const handleCopyExport = () => {
    navigator.clipboard.writeText(exportBoard());
    setShowExport(false);
  };

  return (
    <div style={{ padding: '20px 24px' }}>
      {/* Tab bar */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
      }}>
        <div style={{ display: 'flex', gap: 4 }}>
          {[
            { id: 'oneQB', label: '1QB BOARD' },
            { id: 'superflex', label: 'SUPERFLEX BOARD' },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveFormat(tab.id)}
              style={{
                fontFamily: "'Barlow Condensed', sans-serif",
                fontWeight: 700,
                fontSize: 14,
                letterSpacing: 1.5,
                textTransform: 'uppercase',
                padding: '8px 20px',
                border: '1px solid',
                borderColor: activeFormat === tab.id ? '#f59e0b' : '#2a2d3e',
                borderRadius: 4,
                cursor: 'pointer',
                background: activeFormat === tab.id ? 'rgba(245,158,11,0.15)' : 'transparent',
                color: activeFormat === tab.id ? '#f59e0b' : '#9ca3af',
                transition: 'all 0.15s',
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <button
          onClick={() => setShowExport(true)}
          style={{
            fontFamily: "'Barlow Condensed', sans-serif",
            fontWeight: 700,
            fontSize: 13,
            letterSpacing: 1,
            textTransform: 'uppercase',
            padding: '8px 16px',
            border: '1px solid #2a2d3e',
            borderRadius: 4,
            cursor: 'pointer',
            background: '#1a1d2e',
            color: '#9ca3af',
            transition: 'all 0.15s',
          }}
        >
          Export Board
        </button>
      </div>

      {/* Drag-and-drop list */}
      <DragDropContext onDragEnd={handleDragEnd}>
        <Droppable droppableId="myboard">
          {(provided) => (
            <div
              ref={provided.innerRef}
              {...provided.droppableProps}
              style={{
                background: '#151825',
                borderRadius: 8,
                padding: 8,
                minHeight: 200,
              }}
            >
              {currentBoard.map((player, index) => {
                const posColor = positionColors[player.position] || positionColors.WR;
                const capital = getDraftCapitalInfo(player.draftPick);
                const injured = hasInjuryRisk(player);

                return (
                  <Draggable key={player.id} draggableId={String(player.id)} index={index}>
                    {(provided, snapshot) => (
                      <div
                        ref={provided.innerRef}
                        {...provided.draggableProps}
                        {...provided.dragHandleProps}
                        style={{
                          ...provided.draggableProps.style,
                          background: snapshot.isDragging ? '#252842' : '#1a1d2e',
                          borderRadius: 6,
                          borderLeft: `3px solid ${posColor.border}`,
                          padding: '10px 16px',
                          marginBottom: 4,
                          display: 'flex',
                          alignItems: 'center',
                          gap: 16,
                          transition: snapshot.isDragging ? 'none' : 'background 0.15s',
                        }}
                      >
                        {/* Rank number */}
                        <div style={{
                          fontFamily: "'JetBrains Mono', monospace",
                          fontSize: 18,
                          fontWeight: 700,
                          color: '#4b5563',
                          width: 32,
                          textAlign: 'center',
                          flexShrink: 0,
                        }}>
                          {index + 1}
                        </div>

                        {/* Drag handle dots */}
                        <div style={{
                          color: '#4b5563',
                          fontSize: 16,
                          cursor: 'grab',
                          flexShrink: 0,
                          lineHeight: 1,
                        }}>
                          ⋮⋮
                        </div>

                        {/* Player info */}
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                            <span style={{
                              fontFamily: "'Barlow Condensed', sans-serif",
                              fontWeight: 700,
                              fontSize: 16,
                              color: '#f1f5f9',
                            }}>
                              {player.name}
                            </span>
                            <span style={{
                              fontFamily: "'Barlow Condensed', sans-serif",
                              fontWeight: 600,
                              fontSize: 12,
                              color: posColor.text,
                              background: posColor.bg,
                              padding: '1px 6px',
                              borderRadius: 3,
                            }}>
                              {player.position}
                            </span>
                            {injured && (
                              <span style={{
                                fontFamily: "'JetBrains Mono', monospace",
                                fontSize: 10,
                                fontWeight: 700,
                                color: '#ef4444',
                                background: 'rgba(239,68,68,0.15)',
                                padding: '1px 6px',
                                borderRadius: 3,
                              }}>
                                🚨 INJURY
                              </span>
                            )}
                          </div>
                          <div style={{
                            fontFamily: "'JetBrains Mono', monospace",
                            fontSize: 11,
                            color: '#6b7280',
                          }}>
                            {[player.college, player.draftRound ? `${capital.emoji} R${player.draftRound} #${player.draftPick} ${player.draftTeam || 'TBD'}` : null].filter(Boolean).join(' · ') || 'TBD'}
                          </div>
                        </div>

                        {/* Quick stats */}
                        <div style={{
                          display: 'flex',
                          gap: 16,
                          fontFamily: "'JetBrains Mono', monospace",
                          fontSize: 11,
                          flexShrink: 0,
                        }}>
                          <div style={{ textAlign: 'center' }}>
                            <div style={{ color: '#9ca3af', fontSize: 9, textTransform: 'uppercase' }}>
                              {activeFormat === 'oneQB' ? '1QB' : 'SF'} ADP
                            </div>
                            <div style={{ color: '#f1f5f9', fontWeight: 700 }}>
                              #{player.dynastyADP[activeFormat]}
                            </div>
                          </div>
                          {player.dominatorRating > 0 && (
                            <div style={{ textAlign: 'center' }}>
                              <div style={{ color: '#9ca3af', fontSize: 9, textTransform: 'uppercase' }}>DOM %</div>
                              <div style={{ color: '#f1f5f9', fontWeight: 700 }}>{player.dominatorRating}%</div>
                            </div>
                          )}
                          {player.breakoutAge && (
                            <div style={{ textAlign: 'center' }}>
                              <div style={{ color: '#9ca3af', fontSize: 9, textTransform: 'uppercase' }}>BO AGE</div>
                              <div style={{
                                color: player.breakoutAge <= 20 ? '#f59e0b' : player.breakoutAge <= 21 ? '#22c55e' : '#6b7280',
                                fontWeight: 700,
                              }}>{player.breakoutAge}</div>
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </Draggable>
                );
              })}
              {provided.placeholder}
            </div>
          )}
        </Droppable>
      </DragDropContext>

      {/* Export modal */}
      {showExport && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.8)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 200,
          }}
          onClick={() => setShowExport(false)}
        >
          <div
            onClick={e => e.stopPropagation()}
            style={{
              background: '#0f1117',
              borderRadius: 12,
              border: '1px solid #2a2d3e',
              padding: 24,
              width: '100%',
              maxWidth: 600,
            }}
          >
            <h3 style={{
              fontFamily: "'Barlow Condensed', sans-serif",
              fontWeight: 700,
              fontSize: 18,
              color: '#f59e0b',
              letterSpacing: 1,
              textTransform: 'uppercase',
              marginTop: 0,
              marginBottom: 12,
            }}>Export Board</h3>
            <textarea
              readOnly
              value={exportBoard()}
              style={{
                width: '100%',
                height: 300,
                background: '#1a1d2e',
                color: '#d1d5db',
                border: '1px solid #2a2d3e',
                borderRadius: 6,
                padding: 12,
                fontFamily: "'JetBrains Mono', monospace",
                fontSize: 12,
                resize: 'none',
                outline: 'none',
              }}
            />
            <div style={{ display: 'flex', gap: 8, marginTop: 12, justifyContent: 'flex-end' }}>
              <button
                onClick={() => setShowExport(false)}
                style={{
                  fontFamily: "'Barlow Condensed', sans-serif",
                  fontWeight: 600,
                  padding: '8px 16px',
                  border: '1px solid #2a2d3e',
                  borderRadius: 4,
                  background: 'transparent',
                  color: '#9ca3af',
                  cursor: 'pointer',
                }}
              >
                Close
              </button>
              <button
                onClick={handleCopyExport}
                style={{
                  fontFamily: "'Barlow Condensed', sans-serif",
                  fontWeight: 700,
                  padding: '8px 16px',
                  border: '1px solid #f59e0b',
                  borderRadius: 4,
                  background: 'rgba(245,158,11,0.15)',
                  color: '#f59e0b',
                  cursor: 'pointer',
                }}
              >
                Copy to Clipboard
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MyBoard;
