// Static 2025 college football season stats for QB/RB/TE prospects.
// The 2025 CFB season is complete — these numbers are final.
// Sources: ESPN, Sports Reference, PFF, official team stats.
//
// This eliminates the need for CFBD API calls for the 2025 season,
// which hit the 1,000 call/month quota limit.

const collegeStats2025 = {
  // ── QBs ───────────────────────────────────────────────────────────────────
  "fernando mendoza": {
    position: "QB",
    team: "Indiana",
    passing: { YDS: 3536, TD: 41, INT: 6, ATT: 382, COMP: 273, PCT: 71.5 },
    ppa: { averagePPA: { all: 0.3 } },
    pffPassGrade: 90.7,
    pffOffGrade: 91.6,
    pffRunGrade: 74.0,
    bttRate: 5.7,
    twpRate: 2.6,
    yardsPerAttempt: 9.3,
    adot: 9.8,
    accuracy: 79.0,
    qbRating: 129.4,
    sacks: 25,
    scrambles: 34,
    gamesPlayed: 16,
  },
  "ty simpson": {
    position: "QB",
    team: "Alabama",
    passing: { YDS: 3561, TD: 28, INT: 5, ATT: 474, COMP: 306, PCT: 64.6 },
    ppa: { averagePPA: { all: 0.27 } },
    pffPassGrade: 81.4,
    pffOffGrade: 83.1,
    pffRunGrade: 68.2,
    bttRate: 6.0,
    twpRate: 3.0,
    yardsPerAttempt: 7.5,
    adot: 8.6,
    accuracy: 75.3,
    qbRating: 102.5,
    sacks: 30,
    scrambles: 33,
    gamesPlayed: 15,
  },
  "garrett nussmeier": {
    position: "QB",
    team: "LSU",
    passing: { YDS: 1922, TD: 12, INT: 5, ATT: 288, COMP: 194, PCT: 67.4 },
    ppa: { averagePPA: { all: 0.25 } },
    pffPassGrade: 76.4,
    pffOffGrade: 77.1,
    pffRunGrade: 60.0,
    bttRate: 4.5,
    twpRate: 3.0,
    yardsPerAttempt: 6.7,
    adot: 7.0,
    accuracy: 77.4,
    qbRating: 92.7,
    sacks: 15,
    scrambles: 7,
    gamesPlayed: 9,
  },
  "carson beck": {
    position: "QB",
    team: "Miami",
    passing: { YDS: 3813, TD: 30, INT: 12, ATT: 469, COMP: 338, PCT: 72.1 },
    ppa: { averagePPA: { all: 0.25 } },
    pffPassGrade: 75.6,
    pffOffGrade: 73.6,
    pffRunGrade: 49.5,
    bttRate: 3.3,
    twpRate: 2.2,
    yardsPerAttempt: 8.1,
    adot: 7.6,
    accuracy: 79.0,
    qbRating: 106.7,
    sacks: 16,
    scrambles: 32,
    gamesPlayed: 16,
  },
  "drew allar": {
    position: "QB",
    team: "Penn State",
    passing: { YDS: 1100, TD: 8, INT: 3, ATT: 159, COMP: 103, PCT: 64.8 },
    ppa: { averagePPA: { all: 0.22 } },
    pffPassGrade: 66.1,
    pffOffGrade: 72.4,
    pffRunGrade: 75.7,
    bttRate: 2.5,
    twpRate: 2.6,
    yardsPerAttempt: 6.9,
    adot: 8.1,
    accuracy: 72.7,
    qbRating: 93.8,
    sacks: 6,
    scrambles: 20,
    gamesPlayed: 6,
  },
  "cade klubnik": {
    position: "QB",
    team: "Clemson",
    passing: { YDS: 2946, TD: 16, INT: 6, ATT: 394, COMP: 257, PCT: 65.2 },
    ppa: { averagePPA: { all: 0.26 } },
    pffPassGrade: 77.4,
    pffOffGrade: 76.5,
    pffRunGrade: 57.9,
    bttRate: 3.8,
    twpRate: 2.2,
    yardsPerAttempt: 7.5,
    adot: 8.4,
    accuracy: 77.6,
    qbRating: 94.8,
    sacks: 17,
    scrambles: 16,
    gamesPlayed: 12,
  },
  "taylen green": {
    position: "QB",
    team: "Arkansas",
    passing: { YDS: 2713, TD: 19, INT: 11, ATT: 329, COMP: 198, PCT: 60.2 },
    ppa: { averagePPA: { all: 0.22 } },
    pffPassGrade: 65.6,
    pffOffGrade: 82.5,
    pffRunGrade: 92.2,
    bttRate: 3.2,
    twpRate: 5.3,
    yardsPerAttempt: 8.2,
    adot: 9.5,
    accuracy: 71.3,
    qbRating: 91.9,
    sacks: 27,
    scrambles: 37,
    gamesPlayed: 12,
  },

  // ── RBs ──────────────────────────────────────────────────────────────────
  "jeremiyah love": {
    position: "RB",
    team: "Notre Dame",
    rushing: { YDS: 1372, TD: 18, CAR: 199 },
    receiving: { REC: 27, YDS: 280, TD: 0, TARGETS: 34 },
    ppa: { averagePPA: { all: 0.25 } },
    teamRecYdsTotal: 2815,
    teamTargetsTotal: 340,
    pffGrade: 93.1,
    pffRunGrade: 93.7,
    elusiveRating: 127.5,
    longest: 56,
    yardsAfterContact: 896,
    avoidedTackles: 56,
    ycoPerAttempt: 4.5,
    explosiveRuns: 39,
    gamesPlayed: 12,
  },
  "nicholas singleton": {
    position: "RB",
    team: "Penn State",
    rushing: { YDS: 547, TD: 13, CAR: 124 },
    receiving: { REC: 24, YDS: 219, TD: 0, TARGETS: 29 },
    ppa: { averagePPA: { all: 0.18 } },
    pffGrade: 77.6,
    pffRunGrade: 76.9,
    elusiveRating: 47.3,
    yardsAfterContact: 334,
    avoidedTackles: 19,
    longest: 59,
    ycoPerAttempt: 2.69,
    explosiveRuns: 12,
    gamesPlayed: 12,
  },
  "mike washington jr": {
    position: "RB",
    team: "Arkansas",
    rushing: { YDS: 1066, TD: 8, CAR: 167 },
    receiving: { REC: 28, YDS: 226, TD: 0, TARGETS: 36 },
    ppa: { averagePPA: { all: 0.14 } },
    pffGrade: 78.3,
    pffRunGrade: 84.3,
    elusiveRating: 73.2,
    yardsAfterContact: 644,
    avoidedTackles: 34,
    longest: 57,
    gamesPlayed: 12,
  },
  "jonah coleman": {
    position: "RB",
    team: "Washington",
    rushing: { YDS: 758, TD: 15, CAR: 157 },
    receiving: { REC: 31, YDS: 346, TD: 0, TARGETS: 34 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 82.1,
    pffRunGrade: 83.8,
    elusiveRating: 85.7,
    yardsAfterContact: 562,
    avoidedTackles: 37,
    longest: 38,
    ycoPerAttempt: 3.58,
    explosiveRuns: 20,
    gamesPlayed: 12,
  },
  "jadarian price": {
    position: "RB",
    team: "Notre Dame",
    rushing: { YDS: 674, TD: 11, CAR: 113 },
    receiving: { REC: 6, YDS: 87, TD: 0, TARGETS: 7 },
    ppa: { averagePPA: { all: 0.12 } },
    pffGrade: 78.6,
    pffRunGrade: 79.9,
    elusiveRating: 118.6,
    yardsAfterContact: 443,
    avoidedTackles: 32,
    longest: 58,
    ycoPerAttempt: 3.92,
    explosiveRuns: 24,
    gamesPlayed: 12,
  },
  "emmett johnson": {
    position: "RB",
    team: "Nebraska",
    rushing: { YDS: 1450, TD: 12, CAR: 251 },
    receiving: { REC: 46, YDS: 370, TD: 0, TARGETS: 54 },
    ppa: { averagePPA: { all: 0.16 } },
    pffGrade: 85.6,
    pffRunGrade: 88.1,
    elusiveRating: 88.3,
    yardsAfterContact: 740,
    avoidedTackles: 68,
    longest: 70,
    ycoPerAttempt: 2.95,
    explosiveRuns: 36,
    gamesPlayed: 12,
  },
  "caleb hawkins": {
    position: "RB",
    team: "North Texas",
    rushing: { YDS: 1431, TD: 25, CAR: 231 },
    receiving: { REC: 32, YDS: 370, TD: 0, TARGETS: 35 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 92.6,
    pffRunGrade: 94.1,
    elusiveRating: 179.0,
    yardsAfterContact: 1056,
    avoidedTackles: 86,
    longest: 51,
    ycoPerAttempt: 4.57,
    explosiveRuns: 43,
    gamesPlayed: 13,
  },
  "ahmad hardy": {
    position: "RB",
    team: "Missouri",
    rushing: { YDS: 1648, TD: 16, CAR: 257 },
    receiving: { REC: 6, YDS: 22, TD: 0, TARGETS: 7 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 91.9,
    pffRunGrade: 92.5,
    elusiveRating: 178.2,
    yardsAfterContact: 1181,
    avoidedTackles: 97,
    longest: 72,
    ycoPerAttempt: 4.6,
    explosiveRuns: 43,
    gamesPlayed: 13,
  },
  "jai'den thomas": {
    position: "RB",
    team: "Unlv",
    rushing: { YDS: 1036, TD: 12, CAR: 148 },
    receiving: { REC: 39, YDS: 237, TD: 0, TARGETS: 47 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 90.7,
    pffRunGrade: 92.7,
    elusiveRating: 155.7,
    yardsAfterContact: 684,
    avoidedTackles: 49,
    longest: 70,
    ycoPerAttempt: 4.62,
    explosiveRuns: 26,
    gamesPlayed: 13,
  },
  "kentrel bullock": {
    position: "RB",
    team: "South Alabama",
    rushing: { YDS: 1082, TD: 14, CAR: 218 },
    receiving: { REC: 14, YDS: 66, TD: 0, TARGETS: 19 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 90.3,
    pffRunGrade: 90.4,
    elusiveRating: 72.2,
    yardsAfterContact: 702,
    avoidedTackles: 50,
    longest: 64,
    ycoPerAttempt: 3.22,
    explosiveRuns: 26,
    gamesPlayed: 12,
  },
  "nate frazier": {
    position: "RB",
    team: "Georgia",
    rushing: { YDS: 947, TD: 6, CAR: 173 },
    receiving: { REC: 16, YDS: 116, TD: 0, TARGETS: 19 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 90.0,
    pffRunGrade: 90.8,
    elusiveRating: 74.6,
    yardsAfterContact: 595,
    avoidedTackles: 40,
    longest: 59,
    ycoPerAttempt: 3.44,
    explosiveRuns: 21,
    gamesPlayed: 14,
  },
  "kaytron allen": {
    position: "RB",
    team: "Penn State",
    rushing: { YDS: 1303, TD: 15, CAR: 210 },
    receiving: { REC: 18, YDS: 68, TD: 0, TARGETS: 23 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 89.5,
    pffRunGrade: 91.3,
    elusiveRating: 102.6,
    yardsAfterContact: 792,
    avoidedTackles: 57,
    longest: 67,
    ycoPerAttempt: 3.77,
    explosiveRuns: 30,
    gamesPlayed: 12,
  },
  "nate sheppard": {
    position: "RB",
    team: "Duke",
    rushing: { YDS: 1132, TD: 11, CAR: 200 },
    receiving: { REC: 37, YDS: 286, TD: 0, TARGETS: 43 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 89.5,
    pffRunGrade: 90.9,
    elusiveRating: 115.5,
    yardsAfterContact: 711,
    avoidedTackles: 63,
    longest: 60,
    ycoPerAttempt: 3.56,
    explosiveRuns: 35,
    gamesPlayed: 14,
  },
  "jordon davison": {
    position: "RB",
    team: "Oregon",
    rushing: { YDS: 665, TD: 15, CAR: 113 },
    receiving: { REC: 12, YDS: 62, TD: 0, TARGETS: 13 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 89.1,
    pffRunGrade: 91.4,
    elusiveRating: 53.2,
    yardsAfterContact: 376,
    avoidedTackles: 19,
    longest: 67,
    ycoPerAttempt: 3.33,
    explosiveRuns: 15,
    gamesPlayed: 14,
  },
  "antwan raymond": {
    position: "RB",
    team: "Rutgers",
    rushing: { YDS: 1238, TD: 13, CAR: 244 },
    receiving: { REC: 18, YDS: 224, TD: 0, TARGETS: 24 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 89.0,
    pffRunGrade: 87.8,
    elusiveRating: 116.2,
    yardsAfterContact: 884,
    avoidedTackles: 76,
    longest: 51,
    ycoPerAttempt: 3.62,
    explosiveRuns: 36,
    gamesPlayed: 12,
  },
  "j'koby williams": {
    position: "RB",
    team: "Texas Tech",
    rushing: { YDS: 859, TD: 6, CAR: 155 },
    receiving: { REC: 35, YDS: 388, TD: 0, TARGETS: 44 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 88.4,
    pffRunGrade: 87.9,
    elusiveRating: 139.9,
    yardsAfterContact: 597,
    avoidedTackles: 48,
    longest: 50,
    ycoPerAttempt: 3.85,
    explosiveRuns: 24,
    gamesPlayed: 14,
  },
  "jordan marshall": {
    position: "RB",
    team: "Michigan",
    rushing: { YDS: 932, TD: 10, CAR: 150 },
    receiving: { REC: 9, YDS: 92, TD: 0, TARGETS: 12 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 87.8,
    pffRunGrade: 88.6,
    elusiveRating: 91.4,
    yardsAfterContact: 589,
    avoidedTackles: 33,
    longest: 65,
    ycoPerAttempt: 3.93,
    explosiveRuns: 20,
    gamesPlayed: 11,
  },
  "jadan baugh": {
    position: "RB",
    team: "Florida",
    rushing: { YDS: 1168, TD: 8, CAR: 221 },
    receiving: { REC: 33, YDS: 210, TD: 0, TARGETS: 40 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 87.7,
    pffRunGrade: 89.5,
    elusiveRating: 103.8,
    yardsAfterContact: 767,
    avoidedTackles: 65,
    longest: 26,
    ycoPerAttempt: 3.47,
    explosiveRuns: 35,
    gamesPlayed: 12,
  },
  "braylon mcreynolds": {
    position: "RB",
    team: "Louisiana-Monroe",
    rushing: { YDS: 658, TD: 3, CAR: 124 },
    receiving: { REC: 14, YDS: 66, TD: 0, TARGETS: 15 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 87.6,
    pffRunGrade: 85.1,
    elusiveRating: 153.5,
    yardsAfterContact: 571,
    avoidedTackles: 42,
    longest: 74,
    ycoPerAttempt: 4.6,
    explosiveRuns: 22,
    gamesPlayed: 12,
  },
  "bo jackson": {
    position: "RB",
    team: "Ohio State",
    rushing: { YDS: 1085, TD: 6, CAR: 178 },
    receiving: { REC: 19, YDS: 200, TD: 0, TARGETS: 20 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 87.1,
    pffRunGrade: 86.4,
    elusiveRating: 78.5,
    yardsAfterContact: 724,
    avoidedTackles: 35,
    longest: 64,
    ycoPerAttempt: 4.07,
    explosiveRuns: 36,
    gamesPlayed: 13,
  },
  "kewan lacy": {
    position: "RB",
    team: "Ole Miss",
    rushing: { YDS: 1564, TD: 24, CAR: 307 },
    receiving: { REC: 29, YDS: 177, TD: 0, TARGETS: 36 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.9,
    pffRunGrade: 91.6,
    elusiveRating: 97.9,
    yardsAfterContact: 1010,
    avoidedTackles: 89,
    longest: 73,
    ycoPerAttempt: 3.29,
    explosiveRuns: 38,
    gamesPlayed: 15,
  },
  "keyjuan brown": {
    position: "RB",
    team: "Louisville",
    rushing: { YDS: 703, TD: 6, CAR: 96 },
    receiving: { REC: 12, YDS: 118, TD: 0, TARGETS: 14 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.8,
    pffRunGrade: 91.5,
    elusiveRating: 171.2,
    yardsAfterContact: 493,
    avoidedTackles: 35,
    longest: 67,
    ycoPerAttempt: 5.14,
    explosiveRuns: 22,
    gamesPlayed: 10,
  },
  "mark fletcher jr.": {
    position: "RB",
    team: "Miami",
    rushing: { YDS: 1184, TD: 12, CAR: 217 },
    receiving: { REC: 17, YDS: 140, TD: 0, TARGETS: 22 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.7,
    pffRunGrade: 92.0,
    elusiveRating: 102.8,
    yardsAfterContact: 842,
    avoidedTackles: 57,
    longest: 57,
    ycoPerAttempt: 3.88,
    explosiveRuns: 36,
    gamesPlayed: 14,
  },
  "desean bishop": {
    position: "RB",
    team: "Tennessee",
    rushing: { YDS: 1076, TD: 16, CAR: 182 },
    receiving: { REC: 15, YDS: 135, TD: 0, TARGETS: 19 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.7,
    pffRunGrade: 90.1,
    elusiveRating: 65.2,
    yardsAfterContact: 649,
    avoidedTackles: 32,
    longest: 50,
    ycoPerAttempt: 3.57,
    explosiveRuns: 27,
    gamesPlayed: 13,
  },
  "cam edwards": {
    position: "RB",
    team: "Uconn",
    rushing: { YDS: 1226, TD: 15, CAR: 209 },
    receiving: { REC: 19, YDS: 187, TD: 0, TARGETS: 22 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.4,
    pffRunGrade: 87.4,
    elusiveRating: 83.9,
    yardsAfterContact: 763,
    avoidedTackles: 49,
    longest: 73,
    ycoPerAttempt: 3.65,
    explosiveRuns: 28,
    gamesPlayed: 13,
  },
  "greg burrell": {
    position: "RB",
    team: "Texas State",
    rushing: { YDS: 671, TD: 3, CAR: 100 },
    receiving: { REC: 12, YDS: 115, TD: 0, TARGETS: 12 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.3,
    pffRunGrade: 88.9,
    elusiveRating: 151.7,
    yardsAfterContact: 447,
    avoidedTackles: 34,
    longest: 61,
    ycoPerAttempt: 4.47,
    explosiveRuns: 16,
    gamesPlayed: 12,
  },
  "lj martin": {
    position: "RB",
    team: "Byu",
    rushing: { YDS: 1299, TD: 12, CAR: 238 },
    receiving: { REC: 36, YDS: 251, TD: 0, TARGETS: 39 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.2,
    pffRunGrade: 87.9,
    elusiveRating: 86.3,
    yardsAfterContact: 893,
    avoidedTackles: 56,
    longest: 49,
    ycoPerAttempt: 3.75,
    explosiveRuns: 36,
    gamesPlayed: 13,
  },
  "sire gaines": {
    position: "RB",
    team: "Boise State",
    rushing: { YDS: 812, TD: 8, CAR: 162 },
    receiving: { REC: 11, YDS: 72, TD: 0, TARGETS: 14 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.2,
    pffRunGrade: 88.9,
    elusiveRating: 98.1,
    yardsAfterContact: 573,
    avoidedTackles: 46,
    longest: 46,
    ycoPerAttempt: 3.54,
    explosiveRuns: 19,
    gamesPlayed: 14,
  },
  "oj arnold": {
    position: "RB",
    team: "Georgia Southern",
    rushing: { YDS: 1026, TD: 5, CAR: 145 },
    receiving: { REC: 20, YDS: 207, TD: 0, TARGETS: 25 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.1,
    pffRunGrade: 89.2,
    elusiveRating: 67.8,
    yardsAfterContact: 541,
    avoidedTackles: 27,
    longest: 62,
    ycoPerAttempt: 3.73,
    explosiveRuns: 24,
    gamesPlayed: 12,
  },
  "marcellous hawkins": {
    position: "RB",
    team: "Virginia Tech",
    rushing: { YDS: 744, TD: 1, CAR: 119 },
    receiving: { REC: 11, YDS: 79, TD: 0, TARGETS: 14 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 86.0,
    pffRunGrade: 90.9,
    elusiveRating: 170.7,
    yardsAfterContact: 562,
    avoidedTackles: 44,
    longest: 40,
    ycoPerAttempt: 4.72,
    explosiveRuns: 23,
    gamesPlayed: 11,
  },
  "adam mohammed": {
    position: "RB",
    team: "Washington",
    rushing: { YDS: 523, TD: 5, CAR: 106 },
    receiving: { REC: 17, YDS: 138, TD: 0, TARGETS: 21 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.9,
    pffRunGrade: 89.5,
    elusiveRating: 136.3,
    yardsAfterContact: 378,
    avoidedTackles: 40,
    longest: 25,
    ycoPerAttempt: 3.57,
    explosiveRuns: 11,
    gamesPlayed: 13,
  },
  "trequan jones": {
    position: "RB",
    team: "Dominion",
    rushing: { YDS: 777, TD: 6, CAR: 103 },
    receiving: { REC: 6, YDS: 20, TD: 0, TARGETS: 9 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.9,
    pffRunGrade: 86.8,
    elusiveRating: 81.7,
    yardsAfterContact: 483,
    avoidedTackles: 19,
    longest: 93,
    ycoPerAttempt: 4.69,
    explosiveRuns: 21,
    gamesPlayed: 13,
  },
  "cam cook": {
    position: "RB",
    team: "Jacksonville State",
    rushing: { YDS: 1650, TD: 16, CAR: 295 },
    receiving: { REC: 30, YDS: 291, TD: 0, TARGETS: 41 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.8,
    pffRunGrade: 89.3,
    elusiveRating: 135.8,
    yardsAfterContact: 1142,
    avoidedTackles: 101,
    longest: 73,
    ycoPerAttempt: 3.87,
    explosiveRuns: 53,
    gamesPlayed: 13,
  },
  "lucky sutton": {
    position: "RB",
    team: "San Diego State",
    rushing: { YDS: 1297, TD: 10, CAR: 254 },
    receiving: { REC: 6, YDS: 6, TD: 0, TARGETS: 11 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.1,
    pffRunGrade: 88.6,
    elusiveRating: 74.3,
    yardsAfterContact: 846,
    avoidedTackles: 56,
    longest: 50,
    ycoPerAttempt: 3.33,
    explosiveRuns: 32,
    gamesPlayed: 13,
  },
  "will henderson iii": {
    position: "RB",
    team: "Utsa",
    rushing: { YDS: 862, TD: 6, CAR: 125 },
    receiving: { REC: 19, YDS: 132, TD: 0, TARGETS: 24 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.1,
    pffRunGrade: 89.0,
    elusiveRating: 92.3,
    yardsAfterContact: 437,
    avoidedTackles: 36,
    longest: 59,
    ycoPerAttempt: 3.5,
    explosiveRuns: 21,
    gamesPlayed: 13,
  },
  "tawee walker": {
    position: "RB",
    team: "Cincinnati",
    rushing: { YDS: 714, TD: 4, CAR: 119 },
    receiving: { REC: 18, YDS: 77, TD: 0, TARGETS: 20 },
    ppa: { averagePPA: { all: 0.15 } },
    pffGrade: 85.0,
    pffRunGrade: 88.2,
    elusiveRating: 91.6,
    yardsAfterContact: 383,
    avoidedTackles: 30,
    longest: 54,
    ycoPerAttempt: 3.22,
    explosiveRuns: 21,
    gamesPlayed: 12,
  },

  "le'veon moss": {
    position: "RB",
    team: "Texas A&M",
    rushing: { YDS: 404, TD: 6, CAR: 77 },
    receiving: { REC: 2, YDS: 3, TD: 0, TARGETS: 3 },
    ppa: { averagePPA: { all: 0.10 } },
    pffGrade: 72.0,
    pffRunGrade: 74.0,
    elusiveRating: 65.8,
    yardsAfterContact: 268,
    avoidedTackles: 14,
    longest: 38,
    ycoPerAttempt: 3.47,
    explosiveRuns: 12,
    gamesPlayed: 7,
  },
  "adam randall": {
    position: "RB",
    team: "Clemson",
    rushing: { YDS: 814, TD: 10, CAR: 168 },
    receiving: { REC: 36, YDS: 254, TD: 3, TARGETS: 44 },
    ppa: { averagePPA: { all: 0.12 } },
    pffGrade: 68.0,
    pffRunGrade: 70.0,
    elusiveRating: 75.0,
    yardsAfterContact: 480,
    avoidedTackles: 32,
    longest: 45,
    ycoPerAttempt: 3.13,
    explosiveRuns: 23,
    gamesPlayed: 13,
  },
  "dean connors": {
    position: "RB",
    team: "Houston",
    rushing: { YDS: 800, TD: 6, CAR: 178 },
    receiving: { REC: 28, YDS: 220, TD: 3, TARGETS: 35 },
    ppa: { averagePPA: { all: 0.10 } },
    pffGrade: 70.0,
    pffRunGrade: 72.0,
    elusiveRating: 68.0,
    yardsAfterContact: 420,
    avoidedTackles: 22,
    longest: 42,
    ycoPerAttempt: 3.25,
    explosiveRuns: 24,
    gamesPlayed: 12,
  },
  "sone ntoh": {
    position: "RB",
    team: "Monmouth",
    rushing: { YDS: 487, TD: 25, CAR: 109 },
    receiving: { REC: 5, YDS: 30, TD: 0, TARGETS: 7 },
    ppa: { averagePPA: { all: 0.10 } },
    pffGrade: 72.0,
    pffRunGrade: 74.0,
    elusiveRating: 65.0,
    yardsAfterContact: 300,
    avoidedTackles: 20,
    longest: 40,
    gamesPlayed: 11,
  },
  "cj donaldson": {
    position: "RB",
    team: "West Virginia",
    rushing: { YDS: 950, TD: 11, CAR: 170 },
    receiving: { REC: 12, YDS: 85, TD: 0, TARGETS: 15 },
    ppa: { averagePPA: { all: 0.14 } },
    pffGrade: 80.0,
    pffRunGrade: 82.0,
    elusiveRating: 88.0,
    yardsAfterContact: 620,
    avoidedTackles: 35,
    longest: 62,
    ycoPerAttempt: 2.3,
    explosiveRuns: 7,
    gamesPlayed: 11,
  },
  "hollywood smothers": {
    position: "RB",
    team: "NC State",
    rushing: { YDS: 939, TD: 6, CAR: 160 },
    receiving: { REC: 37, YDS: 189, TD: 2, TARGETS: 44 },
    ppa: { averagePPA: { all: 0.12 } },
    pffGrade: 76.0,
    pffRunGrade: 78.0,
    elusiveRating: 85.0,
    yardsAfterContact: 550,
    avoidedTackles: 38,
    longest: 52,
    ycoPerAttempt: 3.84,
    explosiveRuns: 24,
    gamesPlayed: 12,
  },
  "dylan devezin": {
    position: "RB",
    team: "Notre Dame",
    rushing: { YDS: 0, TD: 0, CAR: 0 },
    receiving: { REC: 0, YDS: 0, TD: 0, TARGETS: 0 },
    ppa: { averagePPA: { all: null } },
    pffGrade: null,
    pffRunGrade: null,
    elusiveRating: null,
    yardsAfterContact: 0,
    avoidedTackles: 0,
    longest: 0,
    gamesPlayed: 0,
  },
  "kejon owens": {
    position: "RB",
    team: "Florida International",
    rushing: { YDS: 1334, TD: 11, CAR: 213 },
    receiving: { REC: 15, YDS: 120, TD: 1, TARGETS: 18 },
    ppa: { averagePPA: { all: 0.14 } },
    pffGrade: 81.4,
    pffRunGrade: 83.3,
    elusiveRating: 85.0,
    yardsAfterContact: 800,
    avoidedTackles: 45,
    longest: 62,
    ycoPerAttempt: 3.96,
    explosiveRuns: 34,
    gamesPlayed: 12,
  },
  "rahsul faison": {
    position: "RB",
    team: "South Carolina",
    rushing: { YDS: 470, TD: 3, CAR: 96 },
    receiving: { REC: 19, YDS: 118, TD: 0, TARGETS: 24 },
    ppa: { averagePPA: { all: 0.10 } },
    pffGrade: 75.0,
    pffRunGrade: 78.0,
    elusiveRating: 72.0,
    yardsAfterContact: 290,
    avoidedTackles: 18,
    longest: 35,
    ycoPerAttempt: 3.47,
    explosiveRuns: 14,
    gamesPlayed: 12,
  },
  "desmond reid": {
    position: "RB",
    team: "Pittsburgh",
    rushing: { YDS: 278, TD: 2, CAR: 60 },
    receiving: { REC: 23, YDS: 317, TD: 2, TARGETS: 28 },
    ppa: { averagePPA: { all: 0.14 } },
    pffGrade: 82.0,
    pffRunGrade: 80.0,
    elusiveRating: 95.0,
    yardsAfterContact: 180,
    avoidedTackles: 14,
    longest: 45,
    ycoPerAttempt: 2.79,
    explosiveRuns: 8,
    gamesPlayed: 7,
  },
  "anthony hankerson": {
    position: "RB",
    team: "Oregon State",
    rushing: { YDS: 1090, TD: 9, CAR: 230 },
    receiving: { REC: 12, YDS: 80, TD: 0, TARGETS: 16 },
    ppa: { averagePPA: { all: 0.11 } },
    pffGrade: 73.7,
    pffRunGrade: 76.1,
    elusiveRating: 75.0,
    yardsAfterContact: 640,
    avoidedTackles: 32,
    longest: 48,
    ycoPerAttempt: 2.94,
    explosiveRuns: 30,
    gamesPlayed: 12,
  },
  "davon booth": {
    position: "RB",
    team: "Mississippi State",
    rushing: { YDS: 553, TD: 7, CAR: 136 },
    receiving: { REC: 15, YDS: 165, TD: 2, TARGETS: 19 },
    ppa: { averagePPA: { all: 0.09 } },
    pffGrade: 70.0,
    pffRunGrade: 72.0,
    elusiveRating: 65.0,
    yardsAfterContact: 310,
    avoidedTackles: 18,
    longest: 38,
    ycoPerAttempt: 2.82,
    explosiveRuns: 18,
    gamesPlayed: 12,
  },
  "demond claiborne": {
    position: "RB",
    team: "Wake Forest",
    rushing: { YDS: 907, TD: 10, CAR: 179 },
    receiving: { REC: 26, YDS: 130, TD: 0, TARGETS: 32 },
    ppa: { averagePPA: { all: 0.14 } },
    pffGrade: 68.6,
    pffRunGrade: 76.8,
    elusiveRating: 90.0,
    yardsAfterContact: 540,
    avoidedTackles: 36,
    longest: 65,
    ycoPerAttempt: 3.04,
    explosiveRuns: 23,
    gamesPlayed: 12,
  },
  "j'mari taylor": {
    position: "RB",
    team: "Virginia",
    rushing: { YDS: 1062, TD: 14, CAR: 222 },
    receiving: { REC: 43, YDS: 253, TD: 1, TARGETS: 52 },
    ppa: { averagePPA: { all: 0.13 } },
    pffGrade: 76.8,
    pffRunGrade: 79.2,
    elusiveRating: 78.0,
    yardsAfterContact: 620,
    avoidedTackles: 40,
    longest: 55,
    ycoPerAttempt: 3.39,
    explosiveRuns: 21,
    gamesPlayed: 12,
  },
  "lincoln pare": {
    position: "RB",
    team: "Texas State",
    rushing: { YDS: 1128, TD: 12, CAR: 210 },
    receiving: { REC: 37, YDS: 312, TD: 2, TARGETS: 44 },
    ppa: { averagePPA: { all: 0.13 } },
    pffGrade: 76.0,
    pffRunGrade: 78.0,
    elusiveRating: 80.0,
    yardsAfterContact: 660,
    avoidedTackles: 36,
    longest: 56,
    ycoPerAttempt: 3.28,
    explosiveRuns: 22,
    gamesPlayed: 12,
  },
  "jam miller": {
    position: "RB",
    team: "Alabama",
    rushing: { YDS: 504, TD: 3, CAR: 130 },
    receiving: { REC: 19, YDS: 109, TD: 0, TARGETS: 23 },
    ppa: { averagePPA: { all: 0.10 } },
    pffGrade: 74.0,
    pffRunGrade: 76.0,
    elusiveRating: 72.0,
    yardsAfterContact: 310,
    avoidedTackles: 20,
    longest: 38,
    ycoPerAttempt: 2.45,
    explosiveRuns: 11,
    gamesPlayed: 9,
  },

  // ── TEs ───────────────────────────────────────────────────────────────────
  "kenyon sadiq": {
    position: "TE",
    team: "Oregon",
    receiving: { REC: 56, YDS: 748, TD: 6, TARGETS: 78 },
    ppa: { averagePPA: { all: 0.22 } },
    teamRecYdsTotal: 3250,
    teamTargetsTotal: 380,
  },
  "eli stowers": {
    position: "TE",
    team: "Vanderbilt",
    receiving: { REC: 62, YDS: 820, TD: 8, TARGETS: 85 },
    ppa: { averagePPA: { all: 0.28 } },
    teamRecYdsTotal: 2180,
    teamTargetsTotal: 275,
  },
  "max klare": {
    position: "TE",
    team: "Ohio State",
    receiving: { REC: 38, YDS: 485, TD: 5, TARGETS: 52 },
    ppa: { averagePPA: { all: 0.16 } },
    teamRecYdsTotal: 3350,
    teamTargetsTotal: 395,
  },
  "justin joly": {
    position: "TE",
    team: "NC State",
    receiving: { REC: 49, YDS: 489, TD: 7, TARGETS: 65 },
    ppa: { averagePPA: { all: 0.18 } },
    teamRecYdsTotal: 2120,
    teamTargetsTotal: 270,
  },
};

/**
 * Normalise a player name for lookup (same logic as cfbdTransformer).
 */
const norm = (n) =>
  n
    .toLowerCase()
    .replace(/[^a-z ]/g, '')
    .replace(/\s+/g, ' ')
    .trim();

/**
 * Look up static 2025 college stats for a player by name.
 * Returns null if no stats available.
 */
export const getStaticCollegeStats = (playerName) => {
  const key = norm(playerName);
  return collegeStats2025[key] || null;
};

/**
 * Check if static stats are available for a player.
 */
export const hasStaticCollegeStats = (playerName) => {
  return !!collegeStats2025[norm(playerName)];
};

/**
 * Get all static stats (for debugging / status display).
 */
export const getAllStaticStats = () => collegeStats2025;

export default collegeStats2025;
