// 2026 NFL Draft data service
// Source: NFL Mock Draft Database — Consensus Big Board (2026-03-24)
// https://www.nflmockdraftdatabase.com/big-boards/2026/consensus-big-board-2026
// Board rank ≈ projected overall pick. Round derived from pick ranges.
// Update with actual picks after the draft (April 23–25, 2026 in Pittsburgh)
//
// Only fantasy-relevant positions (QB, RB, WR, TE) are included below.
// Non-skill positions are omitted since this app only tracks dynasty prospects.

const draftPicks = [
  { pick: 1, round: 1, name: "Fernando Mendoza", position: "QB", college: "Indiana" },
  { pick: 4, round: 1, name: "Jeremiyah Love", position: "RB", college: "Notre Dame" },
  { pick: 8, round: 1, name: "Carnell Tate", position: "WR", college: "Ohio State" },
  { pick: 13, round: 1, name: "Makai Lemon", position: "WR", college: "USC" },
  { pick: 14, round: 1, name: "Jordyn Tyson", position: "WR", college: "Arizona State" },
  { pick: 16, round: 1, name: "Kenyon Sadiq", position: "TE", college: "Oregon" },
  { pick: 26, round: 1, name: "Omar Cooper Jr.", position: "WR", college: "Indiana" },
  { pick: 29, round: 1, name: "Denzel Boston", position: "WR", college: "Washington" },
  { pick: 30, round: 1, name: "Kevin Concepcion", position: "WR", college: "Texas A&M" },
  { pick: 35, round: 2, name: "Ty Simpson", position: "QB", college: "Alabama" },
  { pick: 46, round: 2, name: "Jadarian Price", position: "RB", college: "Notre Dame" },
  { pick: 50, round: 2, name: "Chris Brazzell", position: "WR", college: "Tennessee" },
  { pick: 51, round: 2, name: "Chris Bell", position: "WR", college: "Louisville" },
  { pick: 54, round: 2, name: "Eli Stowers", position: "TE", college: "Vanderbilt" },
  { pick: 56, round: 2, name: "Germie Bernard", position: "WR", college: "Alabama" },
  { pick: 61, round: 2, name: "Zachariah Branch", position: "WR", college: "Georgia" },
  { pick: 64, round: 2, name: "Malachi Fields", position: "WR", college: "Notre Dame" },
  { pick: 65, round: 3, name: "Mike Washington Jr.", position: "RB", college: "Arkansas" },
  { pick: 69, round: 3, name: "Antonio Williams", position: "WR", college: "Clemson" },
  { pick: 75, round: 3, name: "Max Klare", position: "TE", college: "Ohio State" },
  { pick: 77, round: 3, name: "Elijah Sarratt", position: "WR", college: "Indiana" },
  { pick: 79, round: 3, name: "Garrett Nussmeier", position: "QB", college: "LSU" },
  { pick: 84, round: 3, name: "Skyler Bell", position: "WR", college: "UConn" },
  { pick: 86, round: 3, name: "Bryce Lance", position: "WR", college: "North Dakota State" },
  { pick: 88, round: 3, name: "Ted Hurst", position: "WR", college: "Georgia State" },
  { pick: 92, round: 3, name: "Jonah Coleman", position: "RB", college: "Washington" },
  { pick: 93, round: 3, name: "Deion Burks", position: "WR", college: "Oklahoma" },
  { pick: 99, round: 3, name: "Sam Roush", position: "TE", college: "Stanford" },
  { pick: 105, round: 4, name: "Oscar Delp", position: "TE", college: "Georgia" },
  { pick: 108, round: 4, name: "Michael Trigg", position: "TE", college: "Baylor" },
  { pick: 109, round: 4, name: "Ja'Kobi Lane", position: "WR", college: "USC" },
  { pick: 111, round: 4, name: "Emmett Johnson", position: "RB", college: "Nebraska" },
  { pick: 116, round: 4, name: "Drew Allar", position: "QB", college: "Penn State" },
  { pick: 117, round: 4, name: "Justin Joly", position: "TE", college: "NC State" },
  { pick: 118, round: 4, name: "Carson Beck", position: "QB", college: "Miami (FL)" },
  { pick: 121, round: 4, name: "Brenen Thompson", position: "WR", college: "Mississippi State" },
  { pick: 123, round: 4, name: "Nick Singleton", position: "RB", college: "Penn State" },
  { pick: 136, round: 5, name: "Taylen Green", position: "QB", college: "Arkansas" },
  { pick: 139, round: 5, name: "Cole Payton", position: "QB", college: "North Dakota State" },
  { pick: 142, round: 5, name: "Jack Endries", position: "TE", college: "Texas" },
  { pick: 145, round: 5, name: "Josh Cameron", position: "WR", college: "Baylor" },
  { pick: 149, round: 5, name: "Joe Royer", position: "TE", college: "Cincinnati" },
  { pick: 150, round: 5, name: "Kaytron Allen", position: "RB", college: "Penn State" },
  { pick: 152, round: 5, name: "De'Zhaun Stribling", position: "WR", college: "Mississippi" },
  { pick: 156, round: 5, name: "Eli Raridon", position: "TE", college: "Notre Dame" },
  { pick: 161, round: 5, name: "Nate Boerkircher", position: "TE", college: "Texas A&M" },
  { pick: 163, round: 5, name: "Tanner Koziol", position: "TE", college: "Houston" },
  { pick: 165, round: 5, name: "Demond Claiborne", position: "RB", college: "Wake Forest" },
  { pick: 166, round: 5, name: "Will Kacmarek", position: "TE", college: "Ohio State" },
  { pick: 167, round: 5, name: "Kevin Coleman Jr.", position: "WR", college: "Missouri" },
  { pick: 168, round: 5, name: "Eric McAlister", position: "WR", college: "TCU" },
  { pick: 169, round: 5, name: "Dae'Quan Wright", position: "TE", college: "Mississippi" },
  { pick: 170, round: 5, name: "Jeff Caldwell", position: "WR", college: "Cincinnati" },
  { pick: 174, round: 5, name: "Reggie Virgil", position: "WR", college: "Texas Tech" },
  { pick: 179, round: 6, name: "C.J. Daniels", position: "WR", college: "Miami (FL)" },
  { pick: 181, round: 6, name: "Kendrick Law", position: "WR", college: "Kentucky" },
  { pick: 183, round: 6, name: "Cade Klubnik", position: "QB", college: "Clemson" },
  { pick: 186, round: 6, name: "Dallen Bentley", position: "TE", college: "Utah" },
  { pick: 187, round: 6, name: "Marlin Klein", position: "TE", college: "Michigan" },
  { pick: 188, round: 6, name: "Kaelon Black", position: "RB", college: "Indiana" },
  { pick: 190, round: 6, name: "Seth McGowan", position: "RB", college: "Kentucky" },
  { pick: 197, round: 6, name: "Cyrus Allen", position: "WR", college: "Cincinnati" },
  { pick: 199, round: 6, name: "Sawyer Robertson", position: "QB", college: "Baylor" },
  { pick: 200, round: 6, name: "Eli Heidenreich", position: "WR", college: "Navy" },
  { pick: 203, round: 6, name: "Aaron Anderson", position: "WR", college: "LSU" },
  { pick: 212, round: 6, name: "Luke Altmyer", position: "QB", college: "Illinois" },
  { pick: 213, round: 6, name: "John Michael Gyllenborg", position: "TE", college: "Wyoming" },
  { pick: 214, round: 6, name: "Riley Nowakowski", position: "TE", college: "Indiana" },
  { pick: 216, round: 6, name: "J'Mari Taylor", position: "RB", college: "Virginia" },
  { pick: 218, round: 6, name: "Adam Randall", position: "RB", college: "Clemson" },
  { pick: 219, round: 6, name: "Eric Rivers", position: "WR", college: "Georgia Tech" },
  { pick: 220, round: 6, name: "Josh Cuevas", position: "TE", college: "Alabama" },
  { pick: 225, round: 7, name: "Desmond Reid", position: "RB", college: "Pittsburgh" },
  { pick: 227, round: 7, name: "Kaden Wetjen", position: "WR", college: "Iowa" },
  { pick: 228, round: 7, name: "Tyren Montgomery", position: "WR", college: "John Carroll" },
  { pick: 231, round: 7, name: "Jalon Daniels", position: "QB", college: "Kansas" },
  { pick: 233, round: 7, name: "Le'Veon Moss", position: "RB", college: "Texas A&M" },
  { pick: 237, round: 7, name: "Chase Roberts", position: "WR", college: "BYU" },
  { pick: 241, round: 7, name: "Max Bredeson", position: "RB", college: "Michigan" },
  { pick: 243, round: 7, name: "Caleb Douglas", position: "WR", college: "Texas Tech" },
  { pick: 245, round: 7, name: "Noah Whittington", position: "RB", college: "Oregon" },
  { pick: 246, round: 7, name: "Jamarion Miller", position: "RB", college: "Alabama" },
  { pick: 247, round: 7, name: "Barion Brown", position: "WR", college: "LSU" },
  { pick: 249, round: 7, name: "Joe Fagnano", position: "QB", college: "UConn" },
  { pick: 251, round: 7, name: "Roman Hemby", position: "RB", college: "Indiana" },
  { pick: 254, round: 7, name: "DJ Rogers", position: "TE", college: "TCU" },
  { pick: 255, round: 7, name: "Malik Benson", position: "WR", college: "Oregon" },
  { pick: 259, round: 7, name: "Robert Henry Jr.", position: "RB", college: "UTSA" },
  { pick: 261, round: 7, name: "Matthew Hibner", position: "TE", college: "SMU" },
  { pick: 262, round: 7, name: "Diego Pavia", position: "QB", college: "Vanderbilt" },
  { pick: 271, round: 7, name: "Harrison Wallace III", position: "WR", college: "Mississippi" },
  { pick: 272, round: 7, name: "Lewis Bond", position: "WR", college: "Boston College" },
  { pick: 273, round: 7, name: "Colbie Young", position: "WR", college: "Georgia" },
  { pick: 281, round: 7, name: "Devin Voisin", position: "WR", college: "South Alabama" },
  { pick: 284, round: 7, name: "Terion Stewart", position: "RB", college: "Virginia Tech" },
  { pick: 287, round: 7, name: "Romello Brinson", position: "WR", college: "SMU" },
  { pick: 288, round: 7, name: "Zavion Thomas", position: "WR", college: "LSU" },
  { pick: 292, round: 7, name: "Athan Kaliakmanis", position: "QB", college: "Rutgers" },
  { pick: 295, round: 7, name: "Lake McRee", position: "TE", college: "USC" },
  { pick: 296, round: 7, name: "Vinny Anthony II", position: "WR", college: "Wisconsin" },
  { pick: 297, round: 7, name: "Hank Beatty", position: "WR", college: "Illinois" },
  { pick: 302, round: 7, name: "Dean Connors", position: "RB", college: "Houston" },
  { pick: 305, round: 7, name: "Kyron Drones", position: "QB", college: "Virginia Tech" },
  { pick: 317, round: 7, name: "Bauer Sharp", position: "TE", college: "LSU" },
  { pick: 321, round: 7, name: "Kentrel Bullock", position: "RB", college: "South Alabama" },
  { pick: 324, round: 7, name: "Michael Wortham", position: "WR", college: "Montana" },
  { pick: 327, round: 7, name: "Dan Villari", position: "TE", college: "Syracuse" },
  { pick: 330, round: 7, name: "Donaven Mcculley", position: "WR", college: "Michigan" },
  { pick: 331, round: 7, name: "Jaydn Ott", position: "RB", college: "Oklahoma" },
  { pick: 335, round: 7, name: "Miles Kitselman", position: "TE", college: "Tennessee" },
  { pick: 336, round: 7, name: "Chris Hilton", position: "WR", college: "LSU" },
  { pick: 338, round: 7, name: "Byron Cardwell", position: "RB", college: "San Diego State" },
  { pick: 340, round: 7, name: "J.Michael Sturdivant", position: "WR", college: "Florida" },
  { pick: 342, round: 7, name: "Kejon Owens", position: "RB", college: "Florida International" },
  { pick: 346, round: 7, name: "R.J. Maryland", position: "TE", college: "SMU" },
  { pick: 348, round: 7, name: "Keelan Marion", position: "WR", college: "Miami (FL)" },
  { pick: 352, round: 7, name: "Jordan Hudson", position: "WR", college: "SMU" },
  { pick: 356, round: 7, name: "Dane Key", position: "WR", college: "Nebraska" },
  { pick: 357, round: 7, name: "Emmanuel Henderson", position: "WR", college: "Kansas" },
  { pick: 363, round: 7, name: "Noah Thomas", position: "WR", college: "Georgia" },
  { pick: 366, round: 7, name: "Caullin Lacy", position: "WR", college: "Louisville" },
  { pick: 369, round: 7, name: "Haynes King", position: "QB", college: "Georgia Tech" },
  { pick: 375, round: 7, name: "Chip Trayanum", position: "RB", college: "Toledo" },
  { pick: 376, round: 7, name: "Trebor Pena", position: "WR", college: "Penn State" },
  { pick: 377, round: 7, name: "C.J. Donaldson", position: "RB", college: "Ohio State" },
  { pick: 378, round: 7, name: "Lance Mason", position: "TE", college: "Wisconsin" },
  { pick: 380, round: 7, name: "Khalil Dinkins", position: "TE", college: "Penn State" },
  { pick: 383, round: 7, name: "Behren Morton", position: "QB", college: "Texas Tech" },
  { pick: 385, round: 7, name: "Dillon Bell", position: "WR", college: "Georgia" },
  { pick: 387, round: 7, name: "Rahsul Faison", position: "RB", college: "South Carolina" },
  { pick: 396, round: 7, name: "Joey Aguilar", position: "QB", college: "Tennessee" },
  { pick: 405, round: 7, name: "Curtis Allen", position: "RB", college: "Virginia Union" },
  { pick: 410, round: 7, name: "Mark Gronowski", position: "QB", college: "Iowa" },
  { pick: 411, round: 7, name: "Jamal Haynes", position: "RB", college: "Georgia Tech" },
  { pick: 412, round: 7, name: "Seydou Traore", position: "TE", college: "Mississippi State" },
  { pick: 422, round: 7, name: "Jaren Kanak", position: "TE", college: "Oklahoma" },
  { pick: 426, round: 7, name: "Tanner Arkin", position: "TE", college: "Illinois" },
  { pick: 428, round: 7, name: "Jameson Geers", position: "TE", college: "Minnesota" },
  { pick: 430, round: 7, name: "Jalil Farooq", position: "WR", college: "Maryland" },
  { pick: 435, round: 7, name: "Miller Moss", position: "QB", college: "Louisville" },
  { pick: 439, round: 7, name: "Jalen Walthall", position: "WR", college: "Incarnate Word" },
  { pick: 445, round: 7, name: "Braylon James", position: "WR", college: "TCU" },
  { pick: 448, round: 7, name: "Ayden Williams", position: "WR", college: "Mississippi State" },
  { pick: 450, round: 7, name: "Ryan Niblett", position: "WR", college: "Texas" },
  { pick: 451, round: 7, name: "Raymond Cottrell", position: "WR", college: "West Alabama" },
  { pick: 461, round: 7, name: "Nathan Leacock", position: "WR", college: "North Carolina" },
  { pick: 466, round: 7, name: "Grayson Loftis", position: "QB", college: "Charlotte" },
  { pick: 467, round: 7, name: "Sedrick Alexander", position: "RB", college: "Vanderbilt" },
  { pick: 469, round: 7, name: "Davin Stoffel", position: "TE", college: "Illinois" },
  { pick: 473, round: 7, name: "Maalik Murphy", position: "QB", college: "Oregon State" },
  { pick: 476, round: 7, name: "Kobe Prentice", position: "WR", college: "Baylor" },
  { pick: 478, round: 7, name: "Tobias Merriweather", position: "WR", college: "Utah" },
  { pick: 481, round: 7, name: "Kyion Grayes", position: "WR", college: "California" },
  { pick: 482, round: 7, name: "Jaylon Glover", position: "RB", college: "UNLV" },
  { pick: 483, round: 7, name: "C.J. Williams", position: "WR", college: "Stanford" },
  { pick: 489, round: 7, name: "Amari Niblack", position: "TE", college: "Texas A&M" },
  { pick: 490, round: 7, name: "Braylin Presley", position: "WR", college: "Tulsa" },
  { pick: 493, round: 7, name: "Kaleb Brown", position: "WR", college: "UAB" },
  { pick: 496, round: 7, name: "Holden Staes", position: "TE", college: "Indiana" },
  { pick: 497, round: 7, name: "TreVonte Citizen", position: "RB", college: "McNeese State" },
  { pick: 500, round: 7, name: "Antonio Gates Jr.", position: "WR", college: "Delaware State" },
  { pick: 516, round: 7, name: "Squirrel White", position: "WR", college: "Florida State" },
  { pick: 577, round: 7, name: "Christian Leary", position: "WR", college: "Western Michigan" },
  { pick: 600, round: 7, name: "Rara Thomas", position: "WR", college: "Troy" },
  { pick: 609, round: 7, name: "Jared Brown", position: "WR", college: "South Carolina" },
];

// Name aliases: consensus board name → prospect database name
// Handles cases where the big board uses a different name format
const nameAliases = {
  'kevin concepcion': 'kc concepcion',
  'nick singleton': 'nicholas singleton',
  'chris brazzell': 'chris brazzell ii',
  'jmichael sturdivant': 'j michael sturdivant',
  'cj daniels': 'cj daniels',
  'cj donaldson': 'cj donaldson',
};

export const getNameAliases = () => nameAliases;

export const getDraftPicks = () => draftPicks;

export const getDraftPickByName = (name) => draftPicks.find(p => p.name === name);

export const getDraftCapitalLabel = (pick) => {
  if (pick <= 10) return 'Elite';
  if (pick <= 32) return 'Day 1';
  if (pick <= 64) return 'Day 2';
  return 'Day 3';
};

export const getDraftRoundFromPick = (pick) => {
  if (pick <= 32) return 1;
  if (pick <= 64) return 2;
  if (pick <= 100) return 3;
  if (pick <= 135) return 4;
  if (pick <= 176) return 5;
  if (pick <= 220) return 6;
  return 7;
};

export default draftPicks;
