// Mock data for 35 top 2025 NFL Draft rookies
// Shape matches real API response so swapping to live data requires no component changes
import { getReceivingData } from './receivingData';

const mockPlayers = [
  {
    id: 1,
    name: "Cam Ward",
    position: "QB",
    college: "Miami (FL)",
    age: 23,
    height: "6-2",
    weight: 223,
    draftRound: 1,
    draftPick: 1,
    draftIsProjected: true,
    draftTeam: "TEN",
    stats: {
      epa: 0.34,
      cpoe: 4.8,
      passingYards: 4313,
      passingTDs: 39,
      interceptions: 7,
      completionPct: 67.2,
      rushingYards: 262,
      rushingTDs: 3
    },
    breakoutAge: 20,
    dominatorRating: 42.1,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 2, superflex: 1 },
    rank: { oneQB: 3, superflex: 1 },
    receivingByPerspective: null,
    playerComps: ["Patrick Mahomes", "Jayden Daniels"]
  },
  {
    id: 2,
    name: "Shedeur Sanders",
    position: "QB",
    college: "Colorado",
    age: 22,
    height: "6-2",
    weight: 215,
    draftRound: 1,
    draftPick: 5,
    draftIsProjected: true,
    draftTeam: "CLE",
    stats: {
      epa: 0.28,
      cpoe: 3.6,
      passingYards: 4134,
      passingTDs: 37,
      interceptions: 10,
      completionPct: 73.8,
      rushingYards: 145,
      rushingTDs: 2
    },
    breakoutAge: 20,
    dominatorRating: 38.5,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 5, superflex: 2 },
    rank: { oneQB: 6, superflex: 2 },
    receivingByPerspective: null,
    playerComps: ["Jalen Hurts", "Russell Wilson"]
  },
  {
    id: 3,
    name: "Travis Hunter",
    position: "WR",
    college: "Colorado",
    age: 21,
    height: "6-1",
    weight: 185,
    draftRound: 1,
    draftPick: 2,
    draftIsProjected: true,
    draftTeam: "JAX",
    stats: {
      epa: 0.31,
      receptions: 96,
      receivingYards: 1258,
      receivingTDs: 15,
      targets: 123,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 19,
    dominatorRating: 48.7,
    targetShare: 32.1,
    yprr: 3.42,
    yacPerRR: 1.38,
    injuries: [],
    dynastyADP: { oneQB: 1, superflex: 3 },
    rank: { oneQB: 1, superflex: 3 },
    receivingByPerspective: null,
    playerComps: ["Ja'Marr Chase", "DeAndre Hopkins"]
  },
  {
    id: 4,
    name: "Tetairoa McMillan",
    position: "WR",
    college: "Arizona",
    age: 21,
    height: "6-5",
    weight: 212,
    draftRound: 1,
    draftPick: 8,
    draftIsProjected: true,
    draftTeam: "CAR",
    stats: {
      epa: 0.27,
      receptions: 84,
      receivingYards: 1319,
      receivingTDs: 8,
      targets: 119,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 19,
    dominatorRating: 44.2,
    targetShare: 29.8,
    yprr: 3.18,
    yacPerRR: 1.21,
    injuries: [],
    dynastyADP: { oneQB: 3, superflex: 5 },
    rank: { oneQB: 2, superflex: 4 },
    receivingByPerspective: null,
    playerComps: ["Mike Evans", "Tee Higgins"]
  },
  {
    id: 5,
    name: "Ashton Jeanty",
    position: "RB",
    college: "Boise State",
    age: 21,
    height: "5-9",
    weight: 215,
    draftRound: 1,
    draftPick: 7,
    draftIsProjected: true,
    draftTeam: "NYG",
    stats: {
      epa: 0.41,
      rushingYards: 2601,
      rushingTDs: 29,
      receptions: 20,
      receivingYards: 170,
      receivingTDs: 1,
      yardsPerCarry: 7.1
    },
    breakoutAge: 19,
    dominatorRating: 52.3,
    targetShare: 5.2,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 4, superflex: 8 },
    rank: { oneQB: 4, superflex: 7 },
    receivingByPerspective: null,
    playerComps: ["Saquon Barkley", "Barry Sanders"]
  },
  {
    id: 6,
    name: "Luther Burden III",
    position: "WR",
    college: "Missouri",
    age: 21,
    height: "5-11",
    weight: 208,
    draftRound: 1,
    draftPick: 14,
    draftIsProjected: true,
    draftTeam: "IND",
    stats: {
      epa: 0.19,
      receptions: 61,
      receivingYards: 676,
      receivingTDs: 6,
      targets: 97,
      rushingYards: 42,
      rushingTDs: 1
    },
    breakoutAge: 19,
    dominatorRating: 31.8,
    targetShare: 26.4,
    yprr: 2.31,
    yacPerRR: 1.52,
    injuries: [{ type: "Knee (MCL)", date: "2024-10", severity: "moderate", gamesOut: 3 }],
    dynastyADP: { oneQB: 6, superflex: 10 },
    rank: { oneQB: 5, superflex: 9 },
    receivingByPerspective: null,
    playerComps: ["Deebo Samuel", "Tyreek Hill"]
  },
  {
    id: 7,
    name: "Emeka Egbuka",
    position: "WR",
    college: "Ohio State",
    age: 22,
    height: "6-1",
    weight: 205,
    draftRound: 1,
    draftPick: 18,
    draftIsProjected: true,
    draftTeam: "CIN",
    stats: {
      epa: 0.22,
      receptions: 72,
      receivingYards: 1011,
      receivingTDs: 10,
      targets: 101,
      rushingYards: 55,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 28.4,
    targetShare: 22.7,
    yprr: 2.68,
    yacPerRR: 1.15,
    injuries: [],
    dynastyADP: { oneQB: 8, superflex: 14 },
    rank: { oneQB: 7, superflex: 12 },
    receivingByPerspective: null,
    playerComps: ["Chris Olave", "Amari Cooper"]
  },
  {
    id: 8,
    name: "Isaiah Bond",
    position: "WR",
    college: "Texas",
    age: 21,
    height: "5-11",
    weight: 180,
    draftRound: 1,
    draftPick: 22,
    draftIsProjected: true,
    draftTeam: "PIT",
    stats: {
      epa: 0.18,
      receptions: 56,
      receivingYards: 892,
      receivingTDs: 8,
      targets: 82,
      rushingYards: 78,
      rushingTDs: 1
    },
    breakoutAge: 20,
    dominatorRating: 24.1,
    targetShare: 19.3,
    yprr: 2.89,
    yacPerRR: 1.44,
    injuries: [],
    dynastyADP: { oneQB: 10, superflex: 16 },
    rank: { oneQB: 9, superflex: 15 },
    receivingByPerspective: null,
    playerComps: ["Jaylen Waddle", "Marquise Brown"]
  },
  {
    id: 9,
    name: "Omarion Hampton",
    position: "RB",
    college: "North Carolina",
    age: 21,
    height: "6-0",
    weight: 220,
    draftRound: 1,
    draftPick: 24,
    draftIsProjected: true,
    draftTeam: "GB",
    stats: {
      epa: 0.22,
      rushingYards: 1660,
      rushingTDs: 15,
      receptions: 26,
      receivingYards: 234,
      receivingTDs: 2,
      yardsPerCarry: 5.8
    },
    breakoutAge: 20,
    dominatorRating: 35.6,
    targetShare: 7.1,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 7, superflex: 11 },
    rank: { oneQB: 8, superflex: 13 },
    receivingByPerspective: null,
    playerComps: ["Derrick Henry", "Josh Jacobs"]
  },
  {
    id: 10,
    name: "Jalen Milroe",
    position: "QB",
    college: "Alabama",
    age: 22,
    height: "6-2",
    weight: 225,
    draftRound: 1,
    draftPick: 16,
    draftIsProjected: true,
    draftTeam: "MIN",
    stats: {
      epa: 0.18,
      cpoe: 1.2,
      passingYards: 3524,
      passingTDs: 27,
      interceptions: 8,
      completionPct: 63.4,
      rushingYards: 726,
      rushingTDs: 12
    },
    breakoutAge: 22,
    dominatorRating: 34.1,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 12, superflex: 4 },
    rank: { oneQB: 14, superflex: 5 },
    receivingByPerspective: null,
    playerComps: ["Lamar Jackson", "Jalen Hurts"]
  },
  {
    id: 11,
    name: "Mason Graham",
    position: "TE",
    college: "Michigan",
    age: 21,
    height: "6-3",
    weight: 318,
    draftRound: 1,
    draftPick: 3,
    draftIsProjected: true,
    draftTeam: "NYJ",
    stats: {
      epa: 0.05,
      receptions: 0,
      receivingYards: 0,
      receivingTDs: 0,
      targets: 0,
      tackles: 58
    },
    breakoutAge: null,
    dominatorRating: 0,
    targetShare: 0,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 200, superflex: 200 },
    rank: { oneQB: 200, superflex: 200 },
    receivingByPerspective: null,
    playerComps: []
  },
  {
    id: 12,
    name: "Tyler Warren",
    position: "TE",
    college: "Penn State",
    age: 23,
    height: "6-6",
    weight: 260,
    draftRound: 1,
    draftPick: 4,
    draftIsProjected: true,
    draftTeam: "NE",
    stats: {
      epa: 0.24,
      receptions: 104,
      receivingYards: 1233,
      receivingTDs: 8,
      targets: 135,
      rushingYards: 12,
      rushingTDs: 3
    },
    breakoutAge: 22,
    dominatorRating: 36.2,
    targetShare: 28.4,
    yprr: 2.44,
    yacPerRR: 1.18,
    injuries: [],
    dynastyADP: { oneQB: 9, superflex: 13 },
    rank: { oneQB: 10, superflex: 14 },
    receivingByPerspective: null,
    playerComps: ["George Kittle", "Mark Andrews"]
  },
  {
    id: 13,
    name: "Colston Loveland",
    position: "TE",
    college: "Michigan",
    age: 21,
    height: "6-5",
    weight: 245,
    draftRound: 1,
    draftPick: 30,
    draftIsProjected: true,
    draftTeam: "BUF",
    stats: {
      epa: 0.16,
      receptions: 56,
      receivingYards: 789,
      receivingTDs: 5,
      targets: 78,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 20,
    dominatorRating: 22.8,
    targetShare: 18.1,
    yprr: 2.21,
    yacPerRR: 1.08,
    injuries: [],
    dynastyADP: { oneQB: 14, superflex: 20 },
    rank: { oneQB: 13, superflex: 18 },
    receivingByPerspective: null,
    playerComps: ["Kyle Pitts", "Dallas Goedert"]
  },
  {
    id: 14,
    name: "Kaleb Johnson",
    position: "RB",
    college: "Iowa",
    age: 21,
    height: "6-0",
    weight: 225,
    draftRound: 2,
    draftPick: 38,
    draftIsProjected: true,
    draftTeam: "LAC",
    stats: {
      epa: 0.26,
      rushingYards: 1537,
      rushingTDs: 21,
      receptions: 14,
      receivingYards: 118,
      receivingTDs: 0,
      yardsPerCarry: 6.4
    },
    breakoutAge: 21,
    dominatorRating: 29.7,
    targetShare: 4.1,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 11, superflex: 17 },
    rank: { oneQB: 11, superflex: 16 },
    receivingByPerspective: null,
    playerComps: ["Nick Chubb", "Jonathan Taylor"]
  },
  {
    id: 15,
    name: "Tre Harris",
    position: "WR",
    college: "Ole Miss",
    age: 24,
    height: "6-3",
    weight: 205,
    draftRound: 1,
    draftPick: 28,
    draftIsProjected: true,
    draftTeam: "DEN",
    stats: {
      epa: 0.25,
      receptions: 61,
      receivingYards: 1030,
      receivingTDs: 7,
      targets: 88,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 23,
    dominatorRating: 33.4,
    targetShare: 27.2,
    yprr: 2.78,
    yacPerRR: 0.92,
    injuries: [
      { type: "Groin", date: "2024-10", severity: "moderate", gamesOut: 4 },
      { type: "Ankle (High)", date: "2024-11", severity: "moderate", gamesOut: 2 }
    ],
    dynastyADP: { oneQB: 13, superflex: 19 },
    rank: { oneQB: 12, superflex: 17 },
    receivingByPerspective: null,
    playerComps: ["Allen Robinson", "Mike Williams"]
  },
  {
    id: 16,
    name: "Quinn Ewers",
    position: "QB",
    college: "Texas",
    age: 22,
    height: "6-2",
    weight: 210,
    draftRound: 2,
    draftPick: 35,
    draftIsProjected: true,
    draftTeam: "NYG",
    stats: {
      epa: 0.14,
      cpoe: 1.8,
      passingYards: 3189,
      passingTDs: 29,
      interceptions: 11,
      completionPct: 65.1,
      rushingYards: 85,
      rushingTDs: 2
    },
    breakoutAge: 21,
    dominatorRating: 28.3,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [
      { type: "Abdomen (Oblique)", date: "2024-09", severity: "moderate", gamesOut: 3 }
    ],
    dynastyADP: { oneQB: 18, superflex: 7 },
    rank: { oneQB: 20, superflex: 8 },
    receivingByPerspective: null,
    playerComps: ["Kirk Cousins", "Matt Ryan"]
  },
  {
    id: 17,
    name: "Deuce Knight",
    position: "QB",
    college: "Ole Miss",
    age: 20,
    height: "6-3",
    weight: 210,
    draftRound: 2,
    draftPick: 56,
    draftIsProjected: true,
    draftTeam: "PIT",
    stats: {
      epa: 0.11,
      cpoe: 0.6,
      passingYards: 2084,
      passingTDs: 13,
      interceptions: 5,
      completionPct: 58.2,
      rushingYards: 542,
      rushingTDs: 7
    },
    breakoutAge: 20,
    dominatorRating: 22.1,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 25, superflex: 9 },
    rank: { oneQB: 28, superflex: 10 },
    receivingByPerspective: null,
    playerComps: ["Trey Lance", "Josh Allen"]
  },
  {
    id: 18,
    name: "RJ Harvey",
    position: "RB",
    college: "UCF",
    age: 23,
    height: "5-10",
    weight: 205,
    draftRound: 2,
    draftPick: 44,
    draftIsProjected: true,
    draftTeam: "ATL",
    stats: {
      epa: 0.21,
      rushingYards: 1610,
      rushingTDs: 17,
      receptions: 22,
      receivingYards: 198,
      receivingTDs: 1,
      yardsPerCarry: 6.2
    },
    breakoutAge: 22,
    dominatorRating: 31.2,
    targetShare: 5.8,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 15, superflex: 22 },
    rank: { oneQB: 15, superflex: 20 },
    receivingByPerspective: null,
    playerComps: ["Joe Mixon", "Aaron Jones"]
  },
  {
    id: 19,
    name: "Elic Ayomanor",
    position: "WR",
    college: "Stanford",
    age: 21,
    height: "6-2",
    weight: 210,
    draftRound: 1,
    draftPick: 26,
    draftIsProjected: true,
    draftTeam: "HOU",
    stats: {
      epa: 0.20,
      receptions: 68,
      receivingYards: 978,
      receivingTDs: 7,
      targets: 105,
      rushingYards: 12,
      rushingTDs: 0
    },
    breakoutAge: 20,
    dominatorRating: 38.1,
    targetShare: 30.2,
    yprr: 2.52,
    yacPerRR: 1.02,
    injuries: [],
    dynastyADP: { oneQB: 16, superflex: 23 },
    rank: { oneQB: 16, superflex: 21 },
    receivingByPerspective: null,
    playerComps: ["Brandon Aiyuk", "DK Metcalf"]
  },
  {
    id: 20,
    name: "Matthew Golden",
    position: "WR",
    college: "Texas",
    age: 21,
    height: "6-0",
    weight: 195,
    draftRound: 2,
    draftPick: 40,
    draftIsProjected: true,
    draftTeam: "TB",
    stats: {
      epa: 0.17,
      receptions: 62,
      receivingYards: 987,
      receivingTDs: 9,
      targets: 88,
      rushingYards: 34,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 26.3,
    targetShare: 21.2,
    yprr: 2.61,
    yacPerRR: 1.18,
    injuries: [],
    dynastyADP: { oneQB: 17, superflex: 24 },
    rank: { oneQB: 17, superflex: 22 },
    receivingByPerspective: null,
    playerComps: ["Terry McLaurin", "Stefon Diggs"]
  },
  {
    id: 21,
    name: "Jaylin Noel",
    position: "WR",
    college: "Iowa State",
    age: 22,
    height: "5-10",
    weight: 192,
    draftRound: 2,
    draftPick: 48,
    draftIsProjected: true,
    draftTeam: "SF",
    stats: {
      epa: 0.15,
      receptions: 74,
      receivingYards: 924,
      receivingTDs: 6,
      targets: 112,
      rushingYards: 42,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 30.5,
    targetShare: 25.8,
    yprr: 2.12,
    yacPerRR: 1.34,
    injuries: [],
    dynastyADP: { oneQB: 19, superflex: 26 },
    rank: { oneQB: 18, superflex: 24 },
    receivingByPerspective: null,
    playerComps: ["Tyler Lockett", "Brandin Cooks"]
  },
  {
    id: 22,
    name: "Nick Singleton",
    position: "RB",
    college: "Penn State",
    age: 21,
    height: "5-11",
    weight: 220,
    draftRound: 2,
    draftPick: 50,
    draftIsProjected: true,
    draftTeam: "ARI",
    stats: {
      epa: 0.16,
      rushingYards: 1028,
      rushingTDs: 10,
      receptions: 18,
      receivingYards: 152,
      receivingTDs: 1,
      yardsPerCarry: 5.1
    },
    breakoutAge: 19,
    dominatorRating: 21.4,
    targetShare: 4.8,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 20, superflex: 28 },
    rank: { oneQB: 19, superflex: 25 },
    receivingByPerspective: null,
    playerComps: ["Javonte Williams", "D'Andre Swift"]
  },
  {
    id: 23,
    name: "Cam Skattebo",
    position: "RB",
    college: "Arizona State",
    age: 23,
    height: "5-11",
    weight: 215,
    draftRound: 2,
    draftPick: 54,
    draftIsProjected: true,
    draftTeam: "PHI",
    stats: {
      epa: 0.29,
      rushingYards: 1568,
      rushingTDs: 19,
      receptions: 42,
      receivingYards: 504,
      receivingTDs: 3,
      yardsPerCarry: 5.8
    },
    breakoutAge: 22,
    dominatorRating: 40.8,
    targetShare: 10.2,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 21, superflex: 29 },
    rank: { oneQB: 21, superflex: 26 },
    receivingByPerspective: null,
    playerComps: ["Christian McCaffrey", "Alvin Kamara"]
  },
  {
    id: 24,
    name: "Tyleik Williams",
    position: "RB",
    college: "Ohio State",
    age: 22,
    height: "6-3",
    weight: 320,
    draftRound: 1,
    draftPick: 10,
    draftIsProjected: true,
    draftTeam: "NO",
    stats: {
      epa: 0.04,
      rushingYards: 0,
      rushingTDs: 0,
      receptions: 0,
      receivingYards: 0,
      receivingTDs: 0,
      tackles: 48
    },
    breakoutAge: null,
    dominatorRating: 0,
    targetShare: 0,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 200, superflex: 200 },
    rank: { oneQB: 200, superflex: 200 },
    receivingByPerspective: null,
    playerComps: []
  },
  {
    id: 25,
    name: "Jayden Higgins",
    position: "WR",
    college: "Iowa State",
    age: 22,
    height: "6-4",
    weight: 215,
    draftRound: 2,
    draftPick: 42,
    draftIsProjected: true,
    draftTeam: "MIA",
    stats: {
      epa: 0.19,
      receptions: 67,
      receivingYards: 1062,
      receivingTDs: 8,
      targets: 98,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 32.4,
    targetShare: 22.8,
    yprr: 2.48,
    yacPerRR: 0.88,
    injuries: [],
    dynastyADP: { oneQB: 22, superflex: 30 },
    rank: { oneQB: 22, superflex: 27 },
    receivingByPerspective: null,
    playerComps: ["Allen Lazard", "Courtland Sutton"]
  },
  {
    id: 26,
    name: "Conner Weigman",
    position: "QB",
    college: "Texas A&M",
    age: 21,
    height: "6-2",
    weight: 215,
    draftRound: 3,
    draftPick: 68,
    draftIsProjected: true,
    draftTeam: "LV",
    stats: {
      epa: 0.09,
      cpoe: -0.4,
      passingYards: 2712,
      passingTDs: 18,
      interceptions: 9,
      completionPct: 61.8,
      rushingYards: 312,
      rushingTDs: 4
    },
    breakoutAge: 20,
    dominatorRating: 24.8,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [
      { type: "Shoulder (Labrum)", date: "2023-10", severity: "severe", gamesOut: 8 },
      { type: "Foot (Jones Fracture)", date: "2024-09", severity: "severe", gamesOut: 6 }
    ],
    dynastyADP: { oneQB: 30, superflex: 15 },
    rank: { oneQB: 32, superflex: 19 },
    receivingByPerspective: null,
    playerComps: ["Sam Darnold", "Baker Mayfield"]
  },
  {
    id: 27,
    name: "Donovan Ezeiruaku",
    position: "WR",
    college: "Boston College",
    age: 22,
    height: "6-2",
    weight: 250,
    draftRound: 1,
    draftPick: 6,
    draftIsProjected: true,
    draftTeam: "LV",
    stats: {
      epa: 0.12,
      receptions: 0,
      receivingYards: 0,
      receivingTDs: 0,
      targets: 0,
      sacks: 17
    },
    breakoutAge: null,
    dominatorRating: 0,
    targetShare: 0,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 200, superflex: 200 },
    rank: { oneQB: 200, superflex: 200 },
    receivingByPerspective: null,
    playerComps: []
  },
  {
    id: 28,
    name: "Terrance Ferguson",
    position: "TE",
    college: "Oregon",
    age: 22,
    height: "6-5",
    weight: 248,
    draftRound: 2,
    draftPick: 46,
    draftIsProjected: true,
    draftTeam: "DET",
    stats: {
      epa: 0.14,
      receptions: 42,
      receivingYards: 608,
      receivingTDs: 6,
      targets: 58,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 22,
    dominatorRating: 18.2,
    targetShare: 14.5,
    yprr: 2.02,
    yacPerRR: 0.95,
    injuries: [],
    dynastyADP: { oneQB: 24, superflex: 32 },
    rank: { oneQB: 23, superflex: 29 },
    receivingByPerspective: null,
    playerComps: ["Evan Engram", "T.J. Hockenson"]
  },
  {
    id: 29,
    name: "Deontae Lawson",
    position: "RB",
    college: "Alabama",
    age: 22,
    height: "6-1",
    weight: 240,
    draftRound: 1,
    draftPick: 12,
    draftIsProjected: true,
    draftTeam: "DAL",
    stats: {
      epa: 0.03,
      rushingYards: 0,
      rushingTDs: 0,
      receptions: 0,
      receivingYards: 0,
      receivingTDs: 0,
      tackles: 112
    },
    breakoutAge: null,
    dominatorRating: 0,
    targetShare: 0,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 200, superflex: 200 },
    rank: { oneQB: 200, superflex: 200 },
    receivingByPerspective: null,
    playerComps: []
  },
  {
    id: 30,
    name: "Kezerian Mims Jr",
    position: "WR",
    college: "South Florida",
    age: 22,
    height: "6-2",
    weight: 205,
    draftRound: 3,
    draftPick: 72,
    draftIsProjected: true,
    draftTeam: "SEA",
    stats: {
      epa: 0.14,
      receptions: 72,
      receivingYards: 1108,
      receivingTDs: 10,
      targets: 102,
      rushingYards: 18,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 36.8,
    targetShare: 28.4,
    yprr: 2.38,
    yacPerRR: 1.05,
    injuries: [],
    dynastyADP: { oneQB: 26, superflex: 34 },
    rank: { oneQB: 24, superflex: 30 },
    receivingByPerspective: null,
    playerComps: ["Garrett Wilson", "DJ Moore"]
  },
  {
    id: 31,
    name: "Quinshon Judkins",
    position: "RB",
    college: "Ohio State",
    age: 22,
    height: "5-11",
    weight: 220,
    draftRound: 2,
    draftPick: 52,
    draftIsProjected: true,
    draftTeam: "KC",
    stats: {
      epa: 0.18,
      rushingYards: 1060,
      rushingTDs: 14,
      receptions: 20,
      receivingYards: 162,
      receivingTDs: 1,
      yardsPerCarry: 5.2
    },
    breakoutAge: 19,
    dominatorRating: 24.8,
    targetShare: 4.8,
    yprr: null,
    yacPerRR: null,
    injuries: [{ type: "Foot (Lisfranc)", date: "2024-11", severity: "severe", gamesOut: 5 }],
    dynastyADP: { oneQB: 23, superflex: 31 },
    rank: { oneQB: 25, superflex: 31 },
    receivingByPerspective: null,
    playerComps: ["Najee Harris", "Dameon Pierce"]
  },
  {
    id: 32,
    name: "Mitchell Evans",
    position: "TE",
    college: "Notre Dame",
    age: 21,
    height: "6-6",
    weight: 255,
    draftRound: 3,
    draftPick: 78,
    draftIsProjected: true,
    draftTeam: "LAR",
    stats: {
      epa: 0.12,
      receptions: 34,
      receivingYards: 508,
      receivingTDs: 7,
      targets: 48,
      rushingYards: 0,
      rushingTDs: 0
    },
    breakoutAge: 21,
    dominatorRating: 16.4,
    targetShare: 12.1,
    yprr: 1.92,
    yacPerRR: 0.82,
    injuries: [],
    dynastyADP: { oneQB: 28, superflex: 36 },
    rank: { oneQB: 26, superflex: 32 },
    receivingByPerspective: null,
    playerComps: ["Dalton Kincaid", "Cole Kmet"]
  },
  {
    id: 33,
    name: "Jaxson Dart",
    position: "QB",
    college: "Ole Miss",
    age: 23,
    height: "6-2",
    weight: 225,
    draftRound: 3,
    draftPick: 82,
    draftIsProjected: true,
    draftTeam: "SEA",
    stats: {
      epa: 0.22,
      cpoe: 3.2,
      passingYards: 4279,
      passingTDs: 29,
      interceptions: 6,
      completionPct: 71.8,
      rushingYards: 218,
      rushingTDs: 3
    },
    breakoutAge: 22,
    dominatorRating: 31.2,
    targetShare: null,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 32, superflex: 18 },
    rank: { oneQB: 30, superflex: 23 },
    receivingByPerspective: null,
    playerComps: ["Derek Carr", "Matthew Stafford"]
  },
  {
    id: 34,
    name: "Darien Porter",
    position: "WR",
    college: "Iowa State",
    age: 23,
    height: "6-5",
    weight: 215,
    draftRound: 3,
    draftPick: 85,
    draftIsProjected: true,
    draftTeam: "CHI",
    stats: {
      epa: 0.11,
      receptions: 52,
      receivingYards: 768,
      receivingTDs: 5,
      targets: 78,
      rushingYards: 8,
      rushingTDs: 0
    },
    breakoutAge: 22,
    dominatorRating: 22.1,
    targetShare: 18.2,
    yprr: 2.08,
    yacPerRR: 0.78,
    injuries: [{ type: "ACL", date: "2023-11", severity: "severe", gamesOut: 10 }],
    dynastyADP: { oneQB: 29, superflex: 37 },
    rank: { oneQB: 27, superflex: 33 },
    receivingByPerspective: null,
    playerComps: ["Treylon Burks", "N'Keal Harry"]
  },
  {
    id: 35,
    name: "Bhayshul Tuten",
    position: "RB",
    college: "Virginia Tech",
    age: 24,
    height: "5-10",
    weight: 210,
    draftRound: 3,
    draftPick: 88,
    draftIsProjected: true,
    draftTeam: "BAL",
    stats: {
      epa: 0.19,
      rushingYards: 1415,
      rushingTDs: 15,
      receptions: 12,
      receivingYards: 98,
      receivingTDs: 0,
      yardsPerCarry: 5.9
    },
    breakoutAge: 23,
    dominatorRating: 28.4,
    targetShare: 3.2,
    yprr: null,
    yacPerRR: null,
    injuries: [],
    dynastyADP: { oneQB: 27, superflex: 35 },
    rank: { oneQB: 29, superflex: 34 },
    receivingByPerspective: null,
    playerComps: ["Raheem Mostert", "Damien Harris"]
  }
];

// Filter to only fantasy-relevant players (exclude DL/LB)
export const getFantasyRelevantPlayers = () => {
  return mockPlayers
    .filter(p => ['QB', 'RB', 'WR', 'TE'].includes(p.position) && p.rank.oneQB < 200)
    .map(p => ({ ...p, receivingByPerspective: getReceivingData(p.name) || p.receivingByPerspective }));
};

export const getAllPlayers = () => mockPlayers;

export const getPlayerById = (id) => mockPlayers.find(p => p.id === id);

export default mockPlayers;
