// 2026 NFL Draft prospect metadata
// College stats come from CFBD API — this file holds scouting data, projections, and dynasty valuations
// Update projectedPick/projectedTeam after the draft (April 23–25, 2026)
//
// advancedStats: hardcoded college YPRR + target share from PFF / scouting reports.
// These override any calculated values in cfbdTransformer.js.
// Sources: PFF, TruMedia, Steelers Depot, collegefootballnetwork.com, various scouting profiles.

import { getReceivingData } from './receivingData';

const prospects2026Raw = [
  {
    id: 1,
    name: "Jeremiyah Love",
    position: "RB",
    college: "Notre Dame",
    age: 21,
    height: "6-0",
    weight: 212,
    projectedRound: 1,
    projectedPick: 4,
    projectedTeam: "TEN",
    breakoutAge: 19,
    playerComps: ["Saquon Barkley", "Alvin Kamara"],
    dynastyADP: { oneQB: 1, superflex: 1 },
    rank: { oneQB: 1, superflex: 1 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
    stats: { rushingYards: 1136, rushingTDs: 16, yardsPerCarry: 6.1, receptions: 28, receivingYards: 262, receivingTDs: 2, epa: 0.25 },
    dominatorRating: 9.3, // 262 / 2815
  },
  {
    id: 2,
    name: "Fernando Mendoza",
    position: "QB",
    college: "Indiana",
    age: 23,
    height: "6-5",
    weight: 236,
    projectedRound: 1,
    projectedPick: 1,
    projectedTeam: "LV",
    breakoutAge: 22,
    playerComps: ["Jared Goff", "Matt Ryan"],
    dynastyADP: { oneQB: 10, superflex: 2 },
    rank: { oneQB: 10, superflex: 2 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Indiana", year: 2025 },
    stats: { passingYards: 3425, passingTDs: 26, interceptions: 6, completionPct: 68.3, rushingYards: 192, rushingTDs: 3, epa: 0.34, cpoe: null },
  },
  {
    id: 3,
    name: "Carnell Tate",
    position: "WR",
    college: "Ohio State",
    age: 20,
    height: "6-2",
    weight: 192,
    projectedRound: 1,
    projectedPick: 10,
    projectedTeam: "CIN",
    breakoutAge: 19,
    playerComps: ["Chris Olave", "Garrett Wilson"],
    dynastyADP: { oneQB: 2, superflex: 4 },
    rank: { oneQB: 2, superflex: 4 },
    injuries: [],
    advancedStats: { yprr: 3.02, targetShare: 25.0 }, // PFF 2025: 89.0 recv grade, 0% drop rate
    cfbdLookup: { team: "Ohio State", year: 2025 },
  },
  {
    id: 4,
    name: "Jordyn Tyson",
    position: "WR",
    college: "Arizona State",
    age: 21,
    height: "6-0",
    weight: 198,
    projectedRound: 1,
    projectedPick: 11,
    projectedTeam: "MIA",
    breakoutAge: 20,
    playerComps: ["Stefon Diggs", "Keenan Allen"],
    dynastyADP: { oneQB: 3, superflex: 3 },
    rank: { oneQB: 3, superflex: 5 },
    injuries: [{ type: "Knee", date: "2025-10", severity: "Moderate", gamesOut: 3 }],
    advancedStats: { yprr: 2.37, targetShare: 35.0 }, // 2025 (injury-shortened); career 31.2% routes targeted (98th %ile)
    cfbdLookup: { team: "Arizona State", year: 2025 },
  },
  {
    id: 5,
    name: "Makai Lemon",
    position: "WR",
    college: "USC",
    age: 20,
    height: "5-11",
    weight: 192,
    projectedRound: 1,
    projectedPick: 15,
    projectedTeam: "TB",
    breakoutAge: 19,
    playerComps: ["Tyreek Hill", "Jaylen Waddle"],
    dynastyADP: { oneQB: 4, superflex: 5 },
    rank: { oneQB: 4, superflex: 6 },
    injuries: [],
    advancedStats: { yprr: 3.13, targetShare: 30.0 }, // PFF 2025: 91.4 recv grade, Biletnikoff winner; career 3.09 YPRR (1st in class)
    cfbdLookup: { team: "USC", year: 2025 },
  },
  {
    id: 6,
    name: "Kenyon Sadiq",
    position: "TE",
    college: "Oregon",
    age: 22,
    height: "6-3",
    weight: 241,
    projectedRound: 1,
    projectedPick: 14,
    projectedTeam: "BAL",
    breakoutAge: 21,
    playerComps: ["Mark Andrews", "George Kittle"],
    dynastyADP: { oneQB: 5, superflex: 6 },
    rank: { oneQB: 5, superflex: 8 },
    injuries: [],
    advancedStats: { yprr: 1.98, targetShare: 15.0 },
    cfbdLookup: { team: "Oregon", year: 2025 },
    stats: { receptions: 56, receivingYards: 748, receivingTDs: 6, targets: 78, epa: 0.22 },
    dominatorRating: 23.0, // 748 / 3250
  },
  {
    id: 7,
    name: "Nicholas Singleton",
    position: "RB",
    college: "Penn State",
    age: 21,
    height: "6-0",
    weight: 225,
    projectedRound: 2,
    projectedPick: 38,
    projectedTeam: "NYG",
    breakoutAge: 18,
    playerComps: ["Nick Chubb", "Derrick Henry"],
    dynastyADP: { oneQB: 7, superflex: 7 },
    rank: { oneQB: 7, superflex: 11 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Penn State", year: 2025 },
    stats: { rushingYards: 1028, rushingTDs: 10, yardsPerCarry: 5.8, receptions: 16, receivingYards: 178, receivingTDs: 1, epa: 0.18 },
    dominatorRating: 6.1, // 178 / 2920
  },
  {
    id: 8,
    name: "KC Concepcion",
    position: "WR",
    college: "Texas A&M",
    age: 22,
    height: "6-1",
    weight: 200,
    projectedRound: 2,
    projectedPick: 33,
    projectedTeam: "LV",
    breakoutAge: 21,
    playerComps: ["Terry McLaurin", "DK Metcalf"],
    dynastyADP: { oneQB: 6, superflex: 8 },
    rank: { oneQB: 6, superflex: 9 },
    injuries: [],
    advancedStats: { yprr: 2.46, targetShare: 27.0 }, // 2025: 112.9 passer rating when targeted; 88.1% open target rate
    cfbdLookup: { team: "Texas A&M", year: 2025 },
  },
  {
    id: 9,
    name: "Mike Washington Jr.",
    position: "RB",
    college: "Arkansas",
    age: 21,
    height: "5-11",
    weight: 215,
    projectedRound: 2,
    projectedPick: 40,
    projectedTeam: "NYJ",
    breakoutAge: 20,
    playerComps: ["Josh Jacobs", "Marshawn Lynch"],
    dynastyADP: { oneQB: 8, superflex: 9 },
    rank: { oneQB: 8, superflex: 12 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Arkansas", year: 2025 },
    stats: { rushingYards: 892, rushingTDs: 11, yardsPerCarry: 5.2, receptions: 22, receivingYards: 198, receivingTDs: 1, epa: 0.14 },
    dominatorRating: 8.4, // 198 / 2350
  },
  {
    id: 10,
    name: "Ty Simpson",
    position: "QB",
    college: "Alabama",
    age: 21,
    height: "6-1",
    weight: 211,
    projectedRound: 1,
    projectedPick: 18,
    projectedTeam: "MIN",
    breakoutAge: 21,
    playerComps: ["Jalen Hurts", "Dak Prescott"],
    dynastyADP: { oneQB: 15, superflex: 10 },
    rank: { oneQB: 16, superflex: 3 },
    injuries: [],
    advancedStats: null,
    stats: { passingYards: 2753, passingTDs: 18, interceptions: 7, completionPct: 63.4, rushingYards: 510, rushingTDs: 6, epa: 0.22, cpoe: null },
    cfbdLookup: { team: "Alabama", year: 2025 },
  },
  {
    id: 11,
    name: "Denzel Boston",
    position: "WR",
    college: "Washington",
    age: 21,
    height: "6-3",
    weight: 210,
    projectedRound: 1,
    projectedPick: 22,
    projectedTeam: "LAC",
    breakoutAge: 20,
    playerComps: ["Mike Evans", "Brandon Marshall"],
    dynastyADP: { oneQB: 9, superflex: 11 },
    rank: { oneQB: 9, superflex: 13 },
    injuries: [],
    advancedStats: { yprr: 2.44, targetShare: 28.0 }, // 2025 personal best; led Huskies in all receiving categories
    cfbdLookup: { team: "Washington", year: 2025 },
  },
  {
    id: 12,
    name: "Jonah Coleman",
    position: "RB",
    college: "Washington",
    age: 22,
    height: "5-8",
    weight: 220,
    projectedRound: 2,
    projectedPick: 42,
    projectedTeam: "CLE",
    breakoutAge: 20,
    playerComps: ["Josh Jacobs", "Aaron Jones"],
    dynastyADP: { oneQB: 11, superflex: 12 },
    rank: { oneQB: 11, superflex: 15 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Washington", year: 2025 },
    stats: { rushingYards: 1040, rushingTDs: 9, yardsPerCarry: 5.3, receptions: 18, receivingYards: 152, receivingTDs: 1, epa: 0.15 },
    dominatorRating: 5.5, // 152 / 2780
  },
  {
    id: 13,
    name: "Omar Cooper Jr.",
    position: "WR",
    college: "Indiana",
    age: 22,
    height: "6-0",
    weight: 195,
    projectedRound: 2,
    projectedPick: 35,
    projectedTeam: "ARI",
    breakoutAge: 21,
    playerComps: ["Cooper Kupp", "Adam Thielen"],
    dynastyADP: { oneQB: 12, superflex: 14 },
    rank: { oneQB: 12, superflex: 16 },
    injuries: [],
    advancedStats: { yprr: 2.49, targetShare: 21.0 }, // 2025: 13 TDs, 145.2 passer rating when targeted; elite vs zone
    cfbdLookup: { team: "Indiana", year: 2025 },
  },
  {
    id: 14,
    name: "Jadarian Price",
    position: "RB",
    college: "Notre Dame",
    age: 22,
    height: "5-10",
    weight: 200,
    projectedRound: 3,
    projectedPick: 68,
    projectedTeam: "DEN",
    breakoutAge: 21,
    playerComps: ["Javonte Williams", "David Montgomery"],
    dynastyADP: { oneQB: 13, superflex: 15 },
    rank: { oneQB: 13, superflex: 17 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
    stats: { rushingYards: 760, rushingTDs: 8, yardsPerCarry: 5.8, receptions: 20, receivingYards: 185, receivingTDs: 1, epa: 0.12 },
    dominatorRating: 6.6, // 185 / 2815
  },
  {
    id: 15,
    name: "Emmett Johnson",
    position: "RB",
    college: "Nebraska",
    age: 22,
    height: "5-10",
    weight: 210,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: "DAL",
    breakoutAge: 21,
    playerComps: ["Breece Hall", "Tony Pollard"],
    dynastyADP: { oneQB: 14, superflex: 16 },
    rank: { oneQB: 14, superflex: 18 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Nebraska", year: 2025 },
    stats: { rushingYards: 982, rushingTDs: 12, yardsPerCarry: 5.2, receptions: 14, receivingYards: 118, receivingTDs: 1, epa: 0.16 },
    dominatorRating: 4.8, // 118 / 2450
  },
  {
    id: 16,
    name: "Garrett Nussmeier",
    position: "QB",
    college: "LSU",
    age: 22,
    height: "6-2",
    weight: 203,
    projectedRound: 1,
    projectedPick: 25,
    projectedTeam: "CHI",
    breakoutAge: 21,
    playerComps: ["Joe Burrow", "Baker Mayfield"],
    dynastyADP: { oneQB: 18, superflex: 13 },
    rank: { oneQB: 20, superflex: 7 },
    injuries: [{ type: "Shoulder", date: "2025-11", severity: "Minor", gamesOut: 1 }],
    advancedStats: null,
    cfbdLookup: { team: "LSU", year: 2025 },
    stats: { passingYards: 4052, passingTDs: 29, interceptions: 12, completionPct: 66.7, rushingYards: 48, rushingTDs: 2, epa: 0.28, cpoe: null },
  },
  {
    id: 17,
    name: "J. Michael Sturdivant",
    position: "WR",
    college: "Florida",
    age: 22,
    height: "6-1",
    weight: 205,
    projectedRound: 2,
    projectedPick: 44,
    projectedTeam: "DET",
    breakoutAge: 20,
    playerComps: ["Michael Pittman Jr.", "Allen Robinson"],
    dynastyADP: { oneQB: 16, superflex: 17 },
    rank: { oneQB: 15, superflex: 19 },
    injuries: [],
    advancedStats: { yprr: 1.80, targetShare: 18.0 }, // 2025: career-low YPRR at Florida, declining each season
    cfbdLookup: { team: "Florida", year: 2025 },
  },
  {
    id: 18,
    name: "Eli Stowers",
    position: "TE",
    college: "Vanderbilt",
    age: 22,
    height: "6-4",
    weight: 245,
    projectedRound: 2,
    projectedPick: 48,
    projectedTeam: "PIT",
    breakoutAge: 21,
    playerComps: ["Dallas Goedert", "T.J. Hockenson"],
    dynastyADP: { oneQB: 17, superflex: 18 },
    rank: { oneQB: 17, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.55, targetShare: 22.0 },
    cfbdLookup: { team: "Vanderbilt", year: 2025 },
    stats: { receptions: 62, receivingYards: 820, receivingTDs: 8, targets: 85, epa: 0.28 },
    dominatorRating: 37.6, // 820 / 2180
  },
  {
    id: 19,
    name: "Kevin Coleman Jr.",
    position: "WR",
    college: "Florida State",
    age: 21,
    height: "5-11",
    weight: 190,
    projectedRound: 2,
    projectedPick: 52,
    projectedTeam: "KC",
    breakoutAge: 19,
    playerComps: ["Brandin Cooks", "Marquise Brown"],
    dynastyADP: { oneQB: 19, superflex: 19 },
    rank: { oneQB: 18, superflex: 21 },
    injuries: [],
    advancedStats: { yprr: 2.35, targetShare: 22.0 }, // 2025 (Missouri): 66 rec, 732 yds; strong YAC profile
    cfbdLookup: { team: "Florida State", year: 2025 },
  },
  {
    id: 20,
    name: "Carson Beck",
    position: "QB",
    college: "Miami",
    age: 23,
    height: "6-5",
    weight: 233,
    projectedRound: 2,
    projectedPick: 36,
    projectedTeam: "NYJ",
    breakoutAge: 22,
    playerComps: ["Kirk Cousins", "Matthew Stafford"],
    dynastyADP: { oneQB: 22, superflex: 20 },
    rank: { oneQB: 25, superflex: 10 },
    injuries: [{ type: "Elbow (UCL)", date: "2025-01", severity: "Severe", gamesOut: 8 }],
    advancedStats: null,
    cfbdLookup: { team: "Miami", year: 2025 },
    stats: { passingYards: 1802, passingTDs: 12, interceptions: 8, completionPct: 64.4, rushingYards: 28, rushingTDs: 0, epa: 0.08, cpoe: null },
  },
  {
    id: 21,
    name: "Drew Allar",
    position: "QB",
    college: "Penn State",
    age: 22,
    height: "6-5",
    weight: 228,
    projectedRound: 2,
    projectedPick: 45,
    projectedTeam: "NO",
    breakoutAge: 21,
    playerComps: ["Daniel Jones", "Carson Wentz"],
    dynastyADP: { oneQB: 24, superflex: 21 },
    rank: { oneQB: 28, superflex: 14 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Penn State", year: 2025 },
    stats: { passingYards: 3192, passingTDs: 24, interceptions: 7, completionPct: 65.3, rushingYards: 118, rushingTDs: 3, epa: 0.26, cpoe: null },
  },
  {
    id: 22,
    name: "Cade Klubnik",
    position: "QB",
    college: "Clemson",
    age: 22,
    height: "6-2",
    weight: 207,
    projectedRound: 2,
    projectedPick: 55,
    projectedTeam: "DAL",
    breakoutAge: 21,
    playerComps: ["Sam Darnold", "Trevor Lawrence"],
    dynastyADP: { oneQB: 26, superflex: 22 },
    rank: { oneQB: 30, superflex: 15 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Clemson", year: 2025 },
    stats: { passingYards: 3710, passingTDs: 33, interceptions: 7, completionPct: 67.0, rushingYards: 350, rushingTDs: 5, epa: 0.38, cpoe: null },
  },
  {
    id: 23,
    name: "Taylen Green",
    position: "QB",
    college: "Arkansas",
    age: 23,
    height: "6-6",
    weight: 227,
    projectedRound: 2,
    projectedPick: 46,
    projectedTeam: "CLE",
    breakoutAge: 22,
    playerComps: ["Anthony Richardson", "Cam Newton"],
    dynastyADP: { oneQB: 28, superflex: 23 },
    rank: { oneQB: 32, superflex: 17 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Arkansas", year: 2025 },
    stats: { passingYards: 2614, passingTDs: 16, interceptions: 9, completionPct: 60.3, rushingYards: 672, rushingTDs: 8, epa: 0.18, cpoe: null },
  },
  {
    id: 24,
    name: "Max Klare",
    position: "TE",
    college: "Ohio State",
    age: 22,
    height: "6-5",
    weight: 250,
    projectedRound: 2,
    projectedPick: 56,
    projectedTeam: "SF",
    breakoutAge: 21,
    playerComps: ["Kyle Pitts", "Evan Engram"],
    dynastyADP: { oneQB: 20, superflex: 24 },
    rank: { oneQB: 19, superflex: 22 },
    injuries: [],
    advancedStats: { yprr: 1.71, targetShare: 12.0 },
    cfbdLookup: { team: "Ohio State", year: 2025 },
    stats: { receptions: 38, receivingYards: 485, receivingTDs: 5, targets: 52, epa: 0.16 },
    dominatorRating: 14.5, // 485 / 3350
  },
  {
    id: 25,
    name: "Tre Harris",
    position: "WR",
    college: "Ole Miss",
    age: 24,
    height: "6-3",
    weight: 210,
    projectedRound: 2,
    projectedPick: 37,
    projectedTeam: "ARI",
    breakoutAge: 23,
    playerComps: ["Allen Lazard", "Darnell Mooney"],
    dynastyADP: { oneQB: 21, superflex: 25 },
    rank: { oneQB: 21, superflex: 23 },
    injuries: [{ type: "Knee (ACL)", date: "2024-11", severity: "Severe", gamesOut: 10 }],
    advancedStats: { yprr: 5.12, targetShare: 35.0 }, // 2024: historic — 1st Power Conf WR >5.0 YPRR (PFF); 11.06 YPRR vs man
    cfbdLookup: { team: "Ole Miss", year: 2024 },
  },
  {
    id: 26,
    name: "Savion Williams",
    position: "WR",
    college: "TCU",
    age: 22,
    height: "6-5",
    weight: 225,
    projectedRound: 2,
    projectedPick: 53,
    projectedTeam: "HOU",
    breakoutAge: 21,
    playerComps: ["Mike Williams", "Tee Higgins"],
    dynastyADP: { oneQB: 23, superflex: 26 },
    rank: { oneQB: 22, superflex: 24 },
    injuries: [],
    advancedStats: { yprr: 1.62, targetShare: 18.0 }, // Career: historically low for Day 2 WR; gadget/RB hybrid usage
    cfbdLookup: { team: "TCU", year: 2025 },
  },
  {
    id: 27,
    name: "Cole Payton",
    position: "QB",
    college: "North Dakota State",
    age: 23,
    height: "6-3",
    weight: 225,
    projectedRound: 3,
    projectedPick: 75,
    projectedTeam: "CAR",
    breakoutAge: 22,
    playerComps: ["Trey Lance", "Josh Allen"],
    dynastyADP: { oneQB: 30, superflex: 27 },
    rank: { oneQB: 35, superflex: 20 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "North Dakota State", year: 2025 },
    stats: { passingYards: 2680, passingTDs: 22, interceptions: 5, completionPct: 67.4, rushingYards: 480, rushingTDs: 7, epa: 0.30, cpoe: null },
  },
  {
    id: 28,
    name: "Justin Joly",
    position: "TE",
    college: "NC State",
    age: 22,
    height: "6-4",
    weight: 248,
    projectedRound: 3,
    projectedPick: 72,
    projectedTeam: "GB",
    breakoutAge: 21,
    playerComps: ["Pat Freiermuth", "Noah Fant"],
    dynastyADP: { oneQB: 25, superflex: 28 },
    rank: { oneQB: 23, superflex: 25 },
    injuries: [],
    advancedStats: { yprr: 1.90, targetShare: 18.0 },
    cfbdLookup: { team: "NC State", year: 2025 },
    stats: { receptions: 49, receivingYards: 489, receivingTDs: 7, targets: 65, epa: 0.18 },
    dominatorRating: 23.1, // 489 / 2120
  },
  {
    id: 29,
    name: "Isaiah Horton",
    position: "WR",
    college: "Miami",
    age: 21,
    height: "6-2",
    weight: 200,
    projectedRound: 2,
    projectedPick: 58,
    projectedTeam: "PHI",
    breakoutAge: 20,
    playerComps: ["Chris Godwin", "Amari Cooper"],
    dynastyADP: { oneQB: 27, superflex: 29 },
    rank: { oneQB: 24, superflex: 26 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null }, // No PFF college data publicly available
    cfbdLookup: { team: "Miami", year: 2025 },
  },
  {
    id: 30,
    name: "Elic Ayomanor",
    position: "WR",
    college: "Stanford",
    age: 21,
    height: "6-2",
    weight: 205,
    projectedRound: 3,
    projectedPick: 78,
    projectedTeam: "BUF",
    breakoutAge: 19,
    playerComps: ["DeVonta Smith", "Jaxon Smith-Njigba"],
    dynastyADP: { oneQB: 29, superflex: 30 },
    rank: { oneQB: 26, superflex: 27 },
    injuries: [],
    advancedStats: { yprr: 2.10, targetShare: 25.0 }, // College career avg across two 1,000-yd seasons at Stanford
    cfbdLookup: { team: "Stanford", year: 2025 },
  },
  {
    id: 31,
    name: "Devin Neal",
    position: "RB",
    college: "Kansas",
    age: 22,
    height: "5-11",
    weight: 215,
    projectedRound: 3,
    projectedPick: 82,
    projectedTeam: "SEA",
    breakoutAge: 19,
    playerComps: ["Kareem Hunt", "James Conner"],
    dynastyADP: { oneQB: 31, superflex: 31 },
    rank: { oneQB: 27, superflex: 28 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Kansas", year: 2025 },
    stats: { rushingYards: 1148, rushingTDs: 13, yardsPerCarry: 5.4, receptions: 32, receivingYards: 310, receivingTDs: 2, epa: 0.20 },
    dominatorRating: 12.0, // 310 / 2580
  },
  {
    id: 32,
    name: "Jeremiah Smith",
    position: "WR",
    college: "Ohio State",
    age: 19,
    height: "6-3",
    weight: 215,
    projectedRound: 1,
    projectedPick: 5,
    projectedTeam: "NYG",
    breakoutAge: 18,
    playerComps: ["Ja'Marr Chase", "Justin Jefferson"],
    dynastyADP: { oneQB: 33, superflex: 32 },
    rank: { oneQB: 29, superflex: 29 },
    injuries: [],
    advancedStats: { yprr: 3.30, targetShare: 30.0 }, // 2025: 87 rec/109 tgt/1,243 yds; #1 career YPRR among CFB WRs
    cfbdLookup: { team: "Ohio State", year: 2025 },
  },
  {
    id: 33,
    name: "Tetairoa McMillan",
    position: "WR",
    college: "Arizona",
    age: 22,
    height: "6-5",
    weight: 212,
    projectedRound: 1,
    projectedPick: 12,
    projectedTeam: "DAL",
    breakoutAge: 19,
    playerComps: ["Mike Evans", "Tee Higgins"],
    dynastyADP: { oneQB: 32, superflex: 33 },
    rank: { oneQB: 30, superflex: 30 },
    injuries: [],
    advancedStats: { yprr: 2.87, targetShare: 30.0 }, // College final season at Arizona; 1,300+ yd seasons
    cfbdLookup: { team: "Arizona", year: 2025 },
  },
  {
    id: 34,
    name: "Cam Skattebo",
    position: "RB",
    college: "Arizona State",
    age: 24,
    height: "5-11",
    weight: 218,
    projectedRound: 2,
    projectedPick: 60,
    projectedTeam: "IND",
    breakoutAge: 22,
    playerComps: ["Raheem Mostert", "Dameon Pierce"],
    dynastyADP: { oneQB: 34, superflex: 34 },
    rank: { oneQB: 31, superflex: 31 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Arizona State", year: 2025 },
    stats: { rushingYards: 1568, rushingTDs: 19, yardsPerCarry: 5.7, receptions: 42, receivingYards: 502, receivingTDs: 4, epa: 0.32 },
    dominatorRating: 18.7, // 502 / 2680
  },
  {
    id: 35,
    name: "Luther Burden III",
    position: "WR",
    college: "Missouri",
    age: 22,
    height: "5-11",
    weight: 208,
    projectedRound: 1,
    projectedPick: 20,
    projectedTeam: "DAL",
    breakoutAge: 19,
    playerComps: ["Deebo Samuel", "Amon-Ra St. Brown"],
    dynastyADP: { oneQB: 35, superflex: 35 },
    rank: { oneQB: 32, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: 2.50, targetShare: 28.0 }, // 2024 final college season (declined from 3.50 in 2023 due to QB/offense regression)
    cfbdLookup: { team: "Missouri", year: 2025 },
  },
  // Additional WR prospects with PFF receiving perspective data
  {
    id: 36,
    name: "Eric McAlister",
    position: "WR",
    college: "TCU",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.86, targetShare: 27.2 },
    cfbdLookup: { team: "TCU", year: 2025 },
  },
  {
    id: 37,
    name: "Elijah Sarratt",
    position: "WR",
    college: "Indiana",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.70, targetShare: 24.5 },
    cfbdLookup: { team: "Indiana", year: 2025 },
  },
  {
    id: 38,
    name: "Eric Rivers",
    position: "WR",
    college: "Oklahoma State",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.40, targetShare: 23.1 },
    cfbdLookup: { team: "Oklahoma State", year: 2025 },
  },
  {
    id: 39,
    name: "Griffin Wilde",
    position: "WR",
    college: "Navy",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.40, targetShare: 29.2 },
    cfbdLookup: { team: "Navy", year: 2025 },
  },
  {
    id: 40,
    name: "Jared Brown",
    position: "WR",
    college: "Clemson",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.35, targetShare: 24.4 },
    cfbdLookup: { team: "Clemson", year: 2025 },
  },
  {
    id: 41,
    name: "Chase Roberts",
    position: "WR",
    college: "BYU",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.26, targetShare: 24.0 },
    cfbdLookup: { team: "BYU", year: 2025 },
  },
  {
    id: 42,
    name: "Kobe Prentice",
    position: "WR",
    college: "Baylor",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.26, targetShare: 23.2 },
    cfbdLookup: { team: "Baylor", year: 2025 },
  },
  {
    id: 43,
    name: "Ted Hurst",
    position: "WR",
    college: "Virginia Tech",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.25, targetShare: 25.7 },
    cfbdLookup: { team: "Virginia Tech", year: 2025 },
  },
  {
    id: 44,
    name: "Brenen Thompson",
    position: "WR",
    college: "Kansas State",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.21, targetShare: 19.8 },
    cfbdLookup: { team: "Kansas State", year: 2025 },
  },
  {
    id: 45,
    name: "Caullin Lacy",
    position: "WR",
    college: "South Alabama",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.17, targetShare: 23.4 },
    cfbdLookup: { team: "South Alabama", year: 2025 },
  },
  {
    id: 46,
    name: "Jeff Caldwell",
    position: "WR",
    college: "Charlotte",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.16, targetShare: 26.2 },
    cfbdLookup: { team: "Charlotte", year: 2025 },
  },
  {
    id: 47,
    name: "Skyler Bell",
    position: "WR",
    college: "Wisconsin",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.15, targetShare: 25.9 },
    cfbdLookup: { team: "Wisconsin", year: 2025 },
  },
  {
    id: 48,
    name: "Amare Thomas",
    position: "WR",
    college: "Houston",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.15, targetShare: 26.9 },
    cfbdLookup: { team: "Houston", year: 2025 },
  },
  {
    id: 49,
    name: "CJ Daniels",
    position: "WR",
    college: "Miami",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.14, targetShare: 21.0 },
    cfbdLookup: { team: "Miami", year: 2025 },
  },
  {
    id: 50,
    name: "Squirrel White",
    position: "WR",
    college: "Tennessee",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.11, targetShare: 25.5 },
    cfbdLookup: { team: "Tennessee", year: 2025 },
  },
  {
    id: 51,
    name: "Hank Beatty",
    position: "WR",
    college: "Illinois",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.09, targetShare: 23.1 },
    cfbdLookup: { team: "Illinois", year: 2025 },
  },
  {
    id: 52,
    name: "Chris Brazzell II",
    position: "WR",
    college: "Iowa State",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.09, targetShare: 21.8 },
    cfbdLookup: { team: "Iowa State", year: 2025 },
  },
  {
    id: 53,
    name: "Emmanuel Henderson Jr.",
    position: "WR",
    college: "Georgia",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.08, targetShare: 19.1 },
    cfbdLookup: { team: "Georgia", year: 2025 },
  },
  {
    id: 54,
    name: "Cyrus Allen",
    position: "WR",
    college: "Florida State",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.07, targetShare: 21.2 },
    cfbdLookup: { team: "Florida State", year: 2025 },
  },
  {
    id: 55,
    name: "Aaron Anderson",
    position: "WR",
    college: "LSU",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.06, targetShare: 23.9 },
    cfbdLookup: { team: "LSU", year: 2025 },
  },
  {
    id: 56,
    name: "Zachariah Branch",
    position: "WR",
    college: "USC",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.03, targetShare: 26.2 },
    cfbdLookup: { team: "USC", year: 2025 },
  },
  {
    id: 57,
    name: "Malachi Fields",
    position: "WR",
    college: "Notre Dame",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.01, targetShare: 22.9 },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
  },
  {
    id: 58,
    name: "Chris Bell",
    position: "WR",
    college: "Pittsburgh",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 2.01, targetShare: 20.7 },
    cfbdLookup: { team: "Pittsburgh", year: 2025 },
  },
  {
    id: 59,
    name: "Antonio Williams",
    position: "WR",
    college: "Clemson",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.97, targetShare: 23.3 },
    cfbdLookup: { team: "Clemson", year: 2025 },
  },
  {
    id: 60,
    name: "De'Zhaun Stribling",
    position: "WR",
    college: "Oklahoma",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.95, targetShare: 21.3 },
    cfbdLookup: { team: "Oklahoma", year: 2025 },
  },
  {
    id: 61,
    name: "Ja'Kobi Lane",
    position: "WR",
    college: "South Carolina",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.95, targetShare: 21.2 },
    cfbdLookup: { team: "South Carolina", year: 2025 },
  },
  {
    id: 62,
    name: "Jordan Hudson",
    position: "WR",
    college: "TCU",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.93, targetShare: 23.7 },
    cfbdLookup: { team: "TCU", year: 2025 },
  },
  {
    id: 63,
    name: "Devin Voisin",
    position: "WR",
    college: "West Virginia",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.92, targetShare: 21.9 },
    cfbdLookup: { team: "West Virginia", year: 2025 },
  },
  {
    id: 64,
    name: "Lewis Bond",
    position: "WR",
    college: "Texas Tech",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.92, targetShare: 23.2 },
    cfbdLookup: { team: "Texas Tech", year: 2025 },
  },
  {
    id: 65,
    name: "RaRa Thomas",
    position: "WR",
    college: "Tennessee",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.91, targetShare: 20.7 },
    cfbdLookup: { team: "Tennessee", year: 2025 },
  },
  {
    id: 66,
    name: "Barion Brown",
    position: "WR",
    college: "Kentucky",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.91, targetShare: 27.5 },
    cfbdLookup: { team: "Kentucky", year: 2025 },
  },
  {
    id: 67,
    name: "Christian Leary",
    position: "WR",
    college: "Alabama",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.90, targetShare: 24.9 },
    cfbdLookup: { team: "Alabama", year: 2025 },
  },
  {
    id: 68,
    name: "Germie Bernard",
    position: "WR",
    college: "Oklahoma",
    age: null,
    height: null,
    weight: null,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: 1.90, targetShare: 19.9 },
    cfbdLookup: { team: "Oklahoma", year: 2025 },
  },
];

// Merge receiving perspective data into each prospect
const prospects2026 = prospects2026Raw.map(p => ({
  ...p,
  receivingByPerspective: getReceivingData(p.name),
}));

export const getProspects = () => prospects2026;
export const getProspectByName = (name) =>
  prospects2026.find((p) => p.name.toLowerCase() === name.toLowerCase());
export const getProspectById = (id) => prospects2026.find((p) => p.id === id);

export default prospects2026;
