// 2026 NFL Draft prospect metadata
// College stats come from CFBD API — this file holds scouting data, projections, and dynasty valuations
// Update projectedPick/projectedTeam after the draft (April 23–25, 2026)
//
// advancedStats: hardcoded college YPRR + target share from PFF / scouting reports.
// These override any calculated values in cfbdTransformer.js.
// Sources: PFF, TruMedia, Steelers Depot, collegefootballnetwork.com, various scouting profiles.

import { getReceivingData } from './receivingData';

const prospects2026Raw = [
  {
    id: 1,
    name: "Jeremiyah Love",
    position: "RB",
    college: "Notre Dame",
    age: 21,
    height: "6-0",
    weight: 212,
    projectedRound: 1,
    projectedPick: 4,
    projectedTeam: "TEN",
    breakoutAge: 19,
    playerComps: ["Saquon Barkley", "Alvin Kamara"],
    dynastyADP: { oneQB: 1, superflex: 1 },
    rank: { oneQB: 1, superflex: 1 },
    injuries: [],
    advancedStats: { yprr: 1.45, targetShare: 16.7 },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
    stats: { rushingYards: 1372, rushingTDs: 18, yardsPerCarry: 6.9, receptions: 27, receivingYards: 280, receivingTDs: 0, epa: 0.25, pffGrade: 93.1, pffRunGrade: 93.7, elusiveRating: 127.5 },
  },
  {
    id: 2,
    name: "Fernando Mendoza",
    position: "QB",
    college: "Indiana",
    age: 23,
    height: "6-5",
    weight: 236,
    projectedRound: 1,
    projectedPick: 1,
    projectedTeam: "LV",
    breakoutAge: 22,
    playerComps: ["Jared Goff", "Matt Ryan"],
    dynastyADP: { oneQB: 10, superflex: 2 },
    rank: { oneQB: 10, superflex: 2 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Indiana", year: 2025 },
    stats: { passingYards: 3536, passingTDs: 41, INT: 6, completionPct: 71.5, yardsPerAttempt: 9.3, pffPassGrade: 90.7, pffOffGrade: 91.6, bttRate: 5.7, twpRate: 2.6, adot: 9.8, accuracy: 79.0, qbRating: 129.4, sacks: 25, scrambles: 34, gamesPlayed: 16 },
  },
  {
    id: 3,
    name: "Carnell Tate",
    position: "WR",
    college: "Ohio State",
    age: 20,
    height: "6-2",
    weight: 192,
    projectedRound: 1,
    projectedPick: 10,
    projectedTeam: "CIN",
    breakoutAge: 19,
    playerComps: ["Chris Olave", "Garrett Wilson"],
    dynastyADP: { oneQB: 2, superflex: 4 },
    rank: { oneQB: 2, superflex: 4 },
    injuries: [],
    advancedStats: { yprr: 3.02, targetShare: 22.8 }, // PFF 2025: 89.0 recv grade, 0% drop rate
    cfbdLookup: { team: "Ohio State", year: 2025 },
  },
  {
    id: 4,
    name: "Jordyn Tyson",
    position: "WR",
    college: "Arizona State",
    age: 21,
    height: "6-0",
    weight: 198,
    projectedRound: 1,
    projectedPick: 11,
    projectedTeam: "MIA",
    breakoutAge: 20,
    playerComps: ["Stefon Diggs", "Keenan Allen"],
    dynastyADP: { oneQB: 3, superflex: 3 },
    rank: { oneQB: 3, superflex: 5 },
    injuries: [{ type: "Knee", date: "2025-10", severity: "Moderate", gamesOut: 3 }],
    advancedStats: { yprr: 2.37, targetShare: 32.3 }, // 2025 (injury-shortened); career 31.2% routes targeted (98th %ile)
    cfbdLookup: { team: "Arizona State", year: 2025 },
  },
  {
    id: 5,
    name: "Makai Lemon",
    position: "WR",
    college: "USC",
    age: 20,
    height: "5-11",
    weight: 192,
    projectedRound: 1,
    projectedPick: 15,
    projectedTeam: "TB",
    breakoutAge: 19,
    playerComps: ["Tyreek Hill", "Jaylen Waddle"],
    dynastyADP: { oneQB: 4, superflex: 5 },
    rank: { oneQB: 4, superflex: 6 },
    injuries: [],
    advancedStats: { yprr: 3.13, targetShare: 29.5 }, // PFF 2025: 91.4 recv grade, Biletnikoff winner; career 3.09 YPRR (1st in class)
    cfbdLookup: { team: "USC", year: 2025 },
  },
  {
    id: 6,
    name: "Kenyon Sadiq",
    position: "TE",
    college: "Oregon",
    age: 22,
    height: "6-3",
    weight: 241,
    projectedRound: 1,
    projectedPick: 14,
    projectedTeam: "BAL",
    breakoutAge: 21,
    playerComps: ["Mark Andrews", "George Kittle"],
    dynastyADP: { oneQB: 5, superflex: 6 },
    rank: { oneQB: 5, superflex: 8 },
    injuries: [],
    advancedStats: { yprr: 1.98, targetShare: 15.0 },
    cfbdLookup: { team: "Oregon", year: 2025 },
    stats: { receptions: 56, receivingYards: 748, receivingTDs: 6, targets: 78, epa: 0.22 },
    dominatorRating: 23.0, // 748 / 3250
  },
  {
    id: 7,
    name: "Nicholas Singleton",
    position: "RB",
    college: "Penn State",
    age: 21,
    height: "6-0",
    weight: 225,
    projectedRound: 2,
    projectedPick: 38,
    projectedTeam: "NYG",
    breakoutAge: 18,
    playerComps: ["Nick Chubb", "Derrick Henry"],
    dynastyADP: { oneQB: 7, superflex: 7 },
    rank: { oneQB: 7, superflex: 11 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Penn State", year: 2025 },
    stats: { rushingYards: 547, rushingTDs: 13, yardsPerCarry: 4.4, receptions: 24, receivingYards: 219, receivingTDs: 0, epa: 0.18, pffGrade: 77.6, pffRunGrade: 76.9, elusiveRating: 47.3 },
    dominatorRating: 6.1, // 178 / 2920
  },
  {
    id: 8,
    name: "KC Concepcion",
    position: "WR",
    college: "Texas A&M",
    age: 22,
    height: "6-1",
    weight: 200,
    projectedRound: 2,
    projectedPick: 33,
    projectedTeam: "LV",
    breakoutAge: 21,
    playerComps: ["Terry McLaurin", "DK Metcalf"],
    dynastyADP: { oneQB: 6, superflex: 8 },
    rank: { oneQB: 6, superflex: 9 },
    injuries: [],
    advancedStats: { yprr: 2.46, targetShare: 27.0 }, // 2025: 112.9 passer rating when targeted; 88.1% open target rate
    cfbdLookup: { team: "Texas A&M", year: 2025 },
  },
  {
    id: 9,
    name: "Mike Washington Jr.",
    position: "RB",
    college: "Arkansas",
    age: 21,
    height: "5-11",
    weight: 215,
    projectedRound: 2,
    projectedPick: 40,
    projectedTeam: "NYJ",
    breakoutAge: 20,
    playerComps: ["Josh Jacobs", "Marshawn Lynch"],
    dynastyADP: { oneQB: 8, superflex: 9 },
    rank: { oneQB: 8, superflex: 12 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Arkansas", year: 2025 },
    stats: { rushingYards: 1066, rushingTDs: 8, yardsPerCarry: 6.4, receptions: 28, receivingYards: 226, receivingTDs: 0, epa: 0.14, pffGrade: 78.3, pffRunGrade: 84.3, elusiveRating: 73.2 },
    dominatorRating: 8.4, // 198 / 2350
  },
  {
    id: 10,
    name: "Ty Simpson",
    position: "QB",
    college: "Alabama",
    age: 21,
    height: "6-1",
    weight: 211,
    projectedRound: 1,
    projectedPick: 18,
    projectedTeam: "MIN",
    breakoutAge: 21,
    playerComps: ["Jalen Hurts", "Dak Prescott"],
    dynastyADP: { oneQB: 15, superflex: 10 },
    rank: { oneQB: 16, superflex: 3 },
    injuries: [],
    advancedStats: null,
    stats: { passingYards: 3561, passingTDs: 28, INT: 5, completionPct: 64.6, yardsPerAttempt: 7.5, pffPassGrade: 81.4, pffOffGrade: 83.1, bttRate: 6.0, twpRate: 3.0, adot: 8.6, accuracy: 75.3, qbRating: 102.5, sacks: 30, scrambles: 33, gamesPlayed: 15 },
    cfbdLookup: { team: "Alabama", year: 2025 },
  },
  {
    id: 11,
    name: "Denzel Boston",
    position: "WR",
    college: "Washington",
    age: 21,
    height: "6-3",
    weight: 210,
    projectedRound: 1,
    projectedPick: 22,
    projectedTeam: "LAC",
    breakoutAge: 20,
    playerComps: ["Mike Evans", "Brandon Marshall"],
    dynastyADP: { oneQB: 9, superflex: 11 },
    rank: { oneQB: 9, superflex: 13 },
    injuries: [],
    advancedStats: { yprr: 2.44, targetShare: 26.3 }, // 2025 personal best; led Huskies in all receiving categories
    cfbdLookup: { team: "Washington", year: 2025 },
  },
  {
    id: 12,
    name: "Jonah Coleman",
    position: "RB",
    college: "Washington",
    age: 22,
    height: "5-8",
    weight: 220,
    projectedRound: 2,
    projectedPick: 42,
    projectedTeam: "CLE",
    breakoutAge: 20,
    playerComps: ["Josh Jacobs", "Aaron Jones"],
    dynastyADP: { oneQB: 11, superflex: 12 },
    rank: { oneQB: 11, superflex: 15 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Washington", year: 2025 },
    stats: { rushingYards: 758, rushingTDs: 15, yardsPerCarry: 4.8, receptions: 31, receivingYards: 346, receivingTDs: 0, epa: 0.15, pffGrade: 82.1, pffRunGrade: 83.8, elusiveRating: 85.7 },
    dominatorRating: 5.5, // 152 / 2780
  },
  {
    id: 13,
    name: "Omar Cooper Jr.",
    position: "WR",
    college: "Indiana",
    age: 22,
    height: "6-0",
    weight: 195,
    projectedRound: 2,
    projectedPick: 35,
    projectedTeam: "ARI",
    breakoutAge: 21,
    playerComps: ["Cooper Kupp", "Adam Thielen"],
    dynastyADP: { oneQB: 12, superflex: 14 },
    rank: { oneQB: 12, superflex: 16 },
    injuries: [],
    advancedStats: { yprr: 2.55, targetShare: 24.8 }, // 2025: 13 TDs, 145.2 passer rating when targeted; elite vs zone
    cfbdLookup: { team: "Indiana", year: 2025 },
  },
  {
    id: 14,
    name: "Jadarian Price",
    position: "RB",
    college: "Notre Dame",
    age: 22,
    height: "5-10",
    weight: 200,
    projectedRound: 3,
    projectedPick: 68,
    projectedTeam: "DEN",
    breakoutAge: 21,
    playerComps: ["Javonte Williams", "David Montgomery"],
    dynastyADP: { oneQB: 13, superflex: 15 },
    rank: { oneQB: 13, superflex: 17 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
    stats: { rushingYards: 674, rushingTDs: 11, yardsPerCarry: 6.0, receptions: 6, receivingYards: 87, receivingTDs: 0, epa: 0.12, pffGrade: 78.6, pffRunGrade: 79.9, elusiveRating: 118.6 },
    dominatorRating: 6.6, // 185 / 2815
  },
  {
    id: 15,
    name: "Emmett Johnson",
    position: "RB",
    college: "Nebraska",
    age: 22,
    height: "5-10",
    weight: 210,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: "DAL",
    breakoutAge: 21,
    playerComps: ["Breece Hall", "Tony Pollard"],
    dynastyADP: { oneQB: 14, superflex: 16 },
    rank: { oneQB: 14, superflex: 18 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Nebraska", year: 2025 },
    stats: { rushingYards: 1450, rushingTDs: 12, yardsPerCarry: 5.8, receptions: 46, receivingYards: 370, receivingTDs: 0, epa: 0.16, pffGrade: 85.6, pffRunGrade: 88.1, elusiveRating: 88.3 },
    dominatorRating: 4.8, // 118 / 2450
  },
  {
    id: 16,
    name: "Garrett Nussmeier",
    position: "QB",
    college: "LSU",
    age: 22,
    height: "6-2",
    weight: 203,
    projectedRound: 1,
    projectedPick: 25,
    projectedTeam: "CHI",
    breakoutAge: 21,
    playerComps: ["Joe Burrow", "Baker Mayfield"],
    dynastyADP: { oneQB: 18, superflex: 13 },
    rank: { oneQB: 20, superflex: 7 },
    injuries: [{ type: "Shoulder", date: "2025-11", severity: "Minor", gamesOut: 1 }],
    advancedStats: null,
    cfbdLookup: { team: "LSU", year: 2025 },
    stats: { passingYards: 1922, passingTDs: 12, INT: 5, completionPct: 67.4, yardsPerAttempt: 6.7, pffPassGrade: 76.4, pffOffGrade: 77.1, bttRate: 4.5, twpRate: 3.0, adot: 7.0, accuracy: 77.4, qbRating: 92.7, sacks: 15, scrambles: 7, gamesPlayed: 9 },
  },
  {
    id: 17,
    name: "J. Michael Sturdivant",
    position: "WR",
    college: "Florida",
    age: 22,
    height: "6-1",
    weight: 205,
    projectedRound: 2,
    projectedPick: 44,
    projectedTeam: "DET",
    breakoutAge: 20,
    playerComps: ["Michael Pittman Jr.", "Allen Robinson"],
    dynastyADP: { oneQB: 16, superflex: 17 },
    rank: { oneQB: 15, superflex: 19 },
    injuries: [],
    advancedStats: { yprr: 1.32, targetShare: 16.0 }, // 2025: career-low YPRR at Florida, declining each season
    cfbdLookup: { team: "Florida", year: 2025 },
  },
  {
    id: 18,
    name: "Eli Stowers",
    position: "TE",
    college: "Vanderbilt",
    age: 22,
    height: "6-4",
    weight: 245,
    projectedRound: 2,
    projectedPick: 48,
    projectedTeam: "PIT",
    breakoutAge: 21,
    playerComps: ["Dallas Goedert", "T.J. Hockenson"],
    dynastyADP: { oneQB: 17, superflex: 18 },
    rank: { oneQB: 17, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.55, targetShare: 22.0 },
    cfbdLookup: { team: "Vanderbilt", year: 2025 },
    stats: { receptions: 62, receivingYards: 820, receivingTDs: 8, targets: 85, epa: 0.28 },
    dominatorRating: 37.6, // 820 / 2180
  },
  {
    id: 19,
    name: "Kevin Coleman Jr.",
    position: "WR",
    college: "Missouri",
    age: 21,
    height: "5-11",
    weight: 190,
    projectedRound: 2,
    projectedPick: 52,
    projectedTeam: "KC",
    breakoutAge: 19,
    playerComps: ["Brandin Cooks", "Marquise Brown"],
    dynastyADP: { oneQB: 19, superflex: 19 },
    rank: { oneQB: 18, superflex: 21 },
    injuries: [],
    advancedStats: { yprr: 2.23, targetShare: 25.6 }, // 2025 (Missouri): 66 rec, 732 yds; strong YAC profile
    cfbdLookup: { team: "Missouri", year: 2025 },
  },
  {
    id: 20,
    name: "Carson Beck",
    position: "QB",
    college: "Miami",
    age: 23,
    height: "6-5",
    weight: 233,
    projectedRound: 2,
    projectedPick: 36,
    projectedTeam: "NYJ",
    breakoutAge: 22,
    playerComps: ["Kirk Cousins", "Matthew Stafford"],
    dynastyADP: { oneQB: 22, superflex: 20 },
    rank: { oneQB: 25, superflex: 10 },
    injuries: [{ type: "Elbow (UCL)", date: "2025-01", severity: "Severe", gamesOut: 8 }],
    advancedStats: null,
    cfbdLookup: { team: "Miami", year: 2025 },
    stats: { passingYards: 3813, passingTDs: 30, INT: 12, completionPct: 72.1, yardsPerAttempt: 8.1, pffPassGrade: 75.6, pffOffGrade: 73.6, bttRate: 3.3, twpRate: 2.2, adot: 7.6, accuracy: 79.0, qbRating: 106.7, sacks: 16, scrambles: 32, gamesPlayed: 16 },
  },
  {
    id: 21,
    name: "Drew Allar",
    position: "QB",
    college: "Penn State",
    age: 22,
    height: "6-5",
    weight: 228,
    projectedRound: 2,
    projectedPick: 45,
    projectedTeam: "NO",
    breakoutAge: 21,
    playerComps: ["Daniel Jones", "Carson Wentz"],
    dynastyADP: { oneQB: 24, superflex: 21 },
    rank: { oneQB: 28, superflex: 14 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Penn State", year: 2025 },
    stats: { passingYards: 1100, passingTDs: 8, INT: 3, completionPct: 64.8, yardsPerAttempt: 6.9, pffPassGrade: 66.1, pffOffGrade: 72.4, bttRate: 2.5, twpRate: 2.6, adot: 8.1, accuracy: 72.7, qbRating: 93.8, sacks: 6, scrambles: 20, gamesPlayed: 6 },
  },
  {
    id: 22,
    name: "Cade Klubnik",
    position: "QB",
    college: "Clemson",
    age: 22,
    height: "6-2",
    weight: 207,
    projectedRound: 2,
    projectedPick: 55,
    projectedTeam: "DAL",
    breakoutAge: 21,
    playerComps: ["Sam Darnold", "Trevor Lawrence"],
    dynastyADP: { oneQB: 26, superflex: 22 },
    rank: { oneQB: 30, superflex: 15 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Clemson", year: 2025 },
    stats: { passingYards: 2946, passingTDs: 16, INT: 6, completionPct: 65.2, yardsPerAttempt: 7.5, pffPassGrade: 77.4, pffOffGrade: 76.5, bttRate: 3.8, twpRate: 2.2, adot: 8.4, accuracy: 77.6, qbRating: 94.8, sacks: 17, scrambles: 16, gamesPlayed: 12 },
  },
  {
    id: 23,
    name: "Taylen Green",
    position: "QB",
    college: "Arkansas",
    age: 23,
    height: "6-6",
    weight: 227,
    projectedRound: 2,
    projectedPick: 46,
    projectedTeam: "CLE",
    breakoutAge: 22,
    playerComps: ["Anthony Richardson", "Cam Newton"],
    dynastyADP: { oneQB: 28, superflex: 23 },
    rank: { oneQB: 32, superflex: 17 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "Arkansas", year: 2025 },
    stats: { passingYards: 2713, passingTDs: 19, INT: 11, completionPct: 60.2, yardsPerAttempt: 8.2, pffPassGrade: 65.6, pffOffGrade: 82.5, bttRate: 3.2, twpRate: 5.3, adot: 9.5, accuracy: 71.3, qbRating: 91.9, sacks: 27, scrambles: 37, gamesPlayed: 12 },
  },
  {
    id: 24,
    name: "Max Klare",
    position: "TE",
    college: "Ohio State",
    age: 22,
    height: "6-5",
    weight: 250,
    projectedRound: 2,
    projectedPick: 56,
    projectedTeam: "SF",
    breakoutAge: 21,
    playerComps: ["Kyle Pitts", "Evan Engram"],
    dynastyADP: { oneQB: 20, superflex: 24 },
    rank: { oneQB: 19, superflex: 22 },
    injuries: [],
    advancedStats: { yprr: 1.71, targetShare: 12.0 },
    cfbdLookup: { team: "Ohio State", year: 2025 },
    stats: { receptions: 38, receivingYards: 485, receivingTDs: 5, targets: 52, epa: 0.16 },
    dominatorRating: 14.5, // 485 / 3350
  },
  {
    id: 25,
    name: "Tre Harris",
    position: "WR",
    college: "Ole Miss",
    age: 24,
    height: "6-3",
    weight: 210,
    projectedRound: 2,
    projectedPick: 37,
    projectedTeam: "ARI",
    breakoutAge: 23,
    playerComps: ["Allen Lazard", "Darnell Mooney"],
    dynastyADP: { oneQB: 21, superflex: 25 },
    rank: { oneQB: 21, superflex: 23 },
    injuries: [{ type: "Knee (ACL)", date: "2024-11", severity: "Severe", gamesOut: 10 }],
    advancedStats: { yprr: 5.12, targetShare: 35.0 }, // 2024: historic — 1st Power Conf WR >5.0 YPRR (PFF); 11.06 YPRR vs man
    cfbdLookup: { team: "Ole Miss", year: 2024 },
  },
  {
    id: 26,
    name: "Savion Williams",
    position: "WR",
    college: "TCU",
    age: 22,
    height: "6-5",
    weight: 225,
    projectedRound: 2,
    projectedPick: 53,
    projectedTeam: "HOU",
    breakoutAge: 21,
    playerComps: ["Mike Williams", "Tee Higgins"],
    dynastyADP: { oneQB: 23, superflex: 26 },
    rank: { oneQB: 22, superflex: 24 },
    injuries: [],
    advancedStats: { yprr: 1.62, targetShare: 18.0 }, // Career: historically low for Day 2 WR; gadget/RB hybrid usage
    cfbdLookup: { team: "TCU", year: 2025 },
  },
  {
    id: 27,
    name: "Cole Payton",
    position: "QB",
    college: "North Dakota State",
    age: 23,
    height: "6-3",
    weight: 225,
    projectedRound: 3,
    projectedPick: 75,
    projectedTeam: "CAR",
    breakoutAge: 22,
    playerComps: ["Trey Lance", "Josh Allen"],
    dynastyADP: { oneQB: 30, superflex: 27 },
    rank: { oneQB: 35, superflex: 20 },
    injuries: [],
    advancedStats: null,
    cfbdLookup: { team: "North Dakota State", year: 2025 },
    stats: { passingYards: 2680, passingTDs: 22, interceptions: 5, completionPct: 67.4, rushingYards: 480, rushingTDs: 7, epa: 0.30, cpoe: null },
  },
  {
    id: 28,
    name: "Justin Joly",
    position: "TE",
    college: "NC State",
    age: 22,
    height: "6-4",
    weight: 248,
    projectedRound: 3,
    projectedPick: 72,
    projectedTeam: "GB",
    breakoutAge: 21,
    playerComps: ["Pat Freiermuth", "Noah Fant"],
    dynastyADP: { oneQB: 25, superflex: 28 },
    rank: { oneQB: 23, superflex: 25 },
    injuries: [],
    advancedStats: { yprr: 1.90, targetShare: 18.0 },
    cfbdLookup: { team: "NC State", year: 2025 },
    stats: { receptions: 49, receivingYards: 489, receivingTDs: 7, targets: 65, epa: 0.18 },
    dominatorRating: 23.1, // 489 / 2120
  },
  {
    id: 29,
    name: "Isaiah Horton",
    position: "WR",
    college: "Alabama",
    age: 21,
    height: "6-2",
    weight: 200,
    projectedRound: 2,
    projectedPick: 58,
    projectedTeam: "PHI",
    breakoutAge: 20,
    playerComps: ["Chris Godwin", "Amari Cooper"],
    dynastyADP: { oneQB: 27, superflex: 29 },
    rank: { oneQB: 24, superflex: 26 },
    injuries: [],
    advancedStats: { yprr: 1.45, targetShare: 16.7 }, // No PFF college data publicly available
    cfbdLookup: { team: "Alabama", year: 2025 },
  },
  {
    id: 30,
    name: "Elic Ayomanor",
    position: "WR",
    college: "Stanford",
    age: 21,
    height: "6-2",
    weight: 205,
    projectedRound: 3,
    projectedPick: 78,
    projectedTeam: "BUF",
    breakoutAge: 19,
    playerComps: ["DeVonta Smith", "Jaxon Smith-Njigba"],
    dynastyADP: { oneQB: 29, superflex: 30 },
    rank: { oneQB: 26, superflex: 27 },
    injuries: [],
    advancedStats: { yprr: 2.10, targetShare: 25.0 }, // College career avg across two 1,000-yd seasons at Stanford
    cfbdLookup: { team: "Stanford", year: 2025 },
  },
  {
    id: 32,
    name: "Jeremiah Smith",
    position: "WR",
    college: "Ohio State",
    age: 19,
    height: "6-3",
    weight: 215,
    projectedRound: 1,
    projectedPick: 5,
    projectedTeam: "NYG",
    breakoutAge: 18,
    playerComps: ["Ja'Marr Chase", "Justin Jefferson"],
    dynastyADP: { oneQB: 33, superflex: 32 },
    rank: { oneQB: 29, superflex: 29 },
    injuries: [],
    advancedStats: { yprr: 3.43, targetShare: 29.3 }, // 2025: 87 rec/109 tgt/1,243 yds; #1 career YPRR among CFB WRs
    cfbdLookup: { team: "Ohio State", year: 2025 },
  },
  {
    id: 33,
    name: "Tetairoa McMillan",
    position: "WR",
    college: "Arizona",
    age: 22,
    height: "6-5",
    weight: 212,
    projectedRound: 1,
    projectedPick: 12,
    projectedTeam: "DAL",
    breakoutAge: 19,
    playerComps: ["Mike Evans", "Tee Higgins"],
    dynastyADP: { oneQB: 32, superflex: 33 },
    rank: { oneQB: 30, superflex: 30 },
    injuries: [],
    advancedStats: { yprr: 2.87, targetShare: 30.0 }, // College final season at Arizona; 1,300+ yd seasons
    cfbdLookup: { team: "Arizona", year: 2025 },
  },
  {
    id: 35,
    name: "Luther Burden III",
    position: "WR",
    college: "Missouri",
    age: 22,
    height: "5-11",
    weight: 208,
    projectedRound: 1,
    projectedPick: 20,
    projectedTeam: "DAL",
    breakoutAge: 19,
    playerComps: ["Deebo Samuel", "Amon-Ra St. Brown"],
    dynastyADP: { oneQB: 35, superflex: 35 },
    rank: { oneQB: 32, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: 2.50, targetShare: 28.0 }, // 2024 final college season (declined from 3.50 in 2023 due to QB/offense regression)
    cfbdLookup: { team: "Missouri", year: 2025 },
  },
  // Additional WR prospects with PFF receiving perspective data
  {
    id: 36,
    name: "Eric McAlister",
    position: "WR",
    college: "TCU",
    age: 23,
    height: "6-3",
    weight: 218,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["AJ Brown", "DK Metcalf"],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 2.6, targetShare: 26.3 },
    cfbdLookup: { team: "TCU", year: 2025 },
  },
  {
    id: 37,
    name: "Elijah Sarratt",
    position: "WR",
    college: "Indiana",
    age: 24,
    height: "6-1",
    weight: 196,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Cooper Kupp", "Christian Kirk"],
    dynastyADP: { oneQB: 18, superflex: 22 },
    rank: { oneQB: 16, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.39, targetShare: 25.2 },
    cfbdLookup: { team: "Indiana", year: 2025 },
  },
  {
    id: 38,
    name: "Eric Rivers",
    position: "WR",
    college: "Georgia Tech",
    age: 23,
    height: "6-2",
    weight: 207,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["N'Keal Harry", "Miles Boykin"],
    dynastyADP: { oneQB: 58, superflex: 62 },
    rank: { oneQB: 52, superflex: 56 },
    injuries: [],
    advancedStats: { yprr: 2.07, targetShare: 21.0 },
    cfbdLookup: { team: "Georgia Tech", year: 2025 },
  },
  {
    id: 39,
    name: "Griffin Wilde",
    position: "WR",
    college: "Northwestern",
    age: 23,
    height: "6-4",
    weight: 210,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Tyler Boyd", "KJ Hamler"],
    dynastyADP: { oneQB: 58, superflex: 62 },
    rank: { oneQB: 52, superflex: 56 },
    injuries: [],
    advancedStats: { yprr: 2.4, targetShare: 29.2 },
    cfbdLookup: { team: "Northwestern", year: 2025 },
  },
  {
    id: 40,
    name: "Jared Brown",
    position: "WR",
    college: "South Carolina",
    age: 23,
    height: "5-11",
    weight: 185,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Tyquan Thornton", "Kadarius Toney"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 1.65, targetShare: 17.7 },
    cfbdLookup: { team: "South Carolina", year: 2025 },
  },
  {
    id: 41,
    name: "Chase Roberts",
    position: "WR",
    college: "BYU",
    age: 23,
    height: "6-3",
    weight: 202,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Darnell Mooney", "Tyler Lockett"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.35, targetShare: 26.0 },
    cfbdLookup: { team: "BYU", year: 2025 },
  },
  {
    id: 42,
    name: "Kobe Prentice",
    position: "WR",
    college: "Baylor",
    age: 22,
    height: "5-10",
    weight: 175,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Nico Collins", "Jakobi Meyers"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 2.36, targetShare: 21.7 },
    cfbdLookup: { team: "Baylor", year: 2025 },
  },
  {
    id: 43,
    name: "Ted Hurst",
    position: "WR",
    college: "Georgia State",
    age: 24,
    height: "6-4",
    weight: 210,
    projectedRound: 3,
    projectedPick: 85,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Chris Olave", "Romeo Doubs"],
    dynastyADP: { oneQB: 30, superflex: 34 },
    rank: { oneQB: 28, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: 2.42, targetShare: 30.0 },
    cfbdLookup: { team: "Georgia State", year: 2025 },
  },
  {
    id: 44,
    name: "Brenen Thompson",
    position: "WR",
    college: "Mississippi State",
    age: 22,
    height: "6-0",
    weight: 185,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Will Fuller", "DeSean Jackson"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.77, targetShare: 22.9 },
    cfbdLookup: { team: "Mississippi State", year: 2025 },
  },
  {
    id: 45,
    name: "Caullin Lacy",
    position: "WR",
    college: "Louisville",
    age: 25,
    height: "6-0",
    weight: 190,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 24,
    playerComps: ["Jaylen Waddle", "Marvin Harrison Jr."],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 1.64, targetShare: 21.2 },
    cfbdLookup: { team: "Louisville", year: 2025 },
  },
  {
    id: 46,
    name: "Jeff Caldwell",
    position: "WR",
    college: "Cincinnati",
    age: 24,
    height: "6-4",
    weight: 215,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Calvin Ridley", "Courtland Sutton"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.16, targetShare: 26.2 },
    cfbdLookup: { team: "Cincinnati", year: 2025 },
  },
  {
    id: 47,
    name: "Skyler Bell",
    position: "WR",
    college: "UConn",
    age: 24,
    height: "6-0",
    weight: 200,
    projectedRound: 3,
    projectedPick: 85,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Amon-Ra St. Brown", "Keenan Allen"],
    dynastyADP: { oneQB: 30, superflex: 34 },
    rank: { oneQB: 28, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: 3.13, targetShare: 34.5 },
    cfbdLookup: { team: "UConn", year: 2025 },
  },
  {
    id: 48,
    name: "Amare Thomas",
    position: "WR",
    college: "Houston",
    age: 23,
    height: "6-1",
    weight: 200,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Deebo Samuel", "Curtis Samuel"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.43, targetShare: 24.9 },
    cfbdLookup: { team: "Houston", year: 2025 },
  },
  {
    id: 49,
    name: "CJ Daniels",
    position: "WR",
    college: "Miami",
    age: 24,
    height: "6-2",
    weight: 210,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Allen Robinson", "Mike Williams"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 1.73, targetShare: 20.8 },
    cfbdLookup: { team: "Miami", year: 2025 },
  },
  {
    id: 50,
    name: "Squirrel White",
    position: "WR",
    college: "Florida State",
    age: 23,
    height: "5-10",
    weight: 178,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Rondale Moore", "Tyquan Thornton"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 0.55, targetShare: 16.8 },
    cfbdLookup: { team: "Florida State", year: 2025 },
  },
  {
    id: 51,
    name: "Hank Beatty",
    position: "WR",
    college: "Illinois",
    age: 23,
    height: "6-2",
    weight: 207,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Darnell Mooney", "Tyler Boyd"],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 2.51, targetShare: 25.7 },
    cfbdLookup: { team: "Illinois", year: 2025 },
  },
  {
    id: 52,
    name: "Chris Brazzell II",
    position: "WR",
    college: "Tennessee",
    age: 23,
    height: "6-3",
    weight: 215,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Mike Evans", "Brandon Marshall"],
    dynastyADP: { oneQB: 18, superflex: 22 },
    rank: { oneQB: 16, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.57, targetShare: 21.9 },
    cfbdLookup: { team: "Tennessee", year: 2025 },
  },
  {
    id: 53,
    name: "Emmanuel Henderson Jr.",
    position: "WR",
    college: "Kansas",
    age: 22,
    height: "6-1",
    weight: 195,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["DeSean Jackson", "Ted Ginn Jr."],
    dynastyADP: { oneQB: 58, superflex: 62 },
    rank: { oneQB: 52, superflex: 56 },
    injuries: [],
    advancedStats: { yprr: 2.31, targetShare: 20.5 },
    cfbdLookup: { team: "Kansas", year: 2025 },
  },
  {
    id: 54,
    name: "Cyrus Allen",
    position: "WR",
    college: "Cincinnati",
    age: 22,
    height: "6-1",
    weight: 198,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Tyler Boyd", "Diontae Johnson"],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 2.42, targetShare: 25.3 },
    cfbdLookup: { team: "Cincinnati", year: 2025 },
  },
  {
    id: 55,
    name: "Aaron Anderson",
    position: "WR",
    college: "LSU",
    age: 22,
    height: "5-9",
    weight: 180,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Tyreek Hill", "Jaylen Waddle"],
    dynastyADP: { oneQB: 58, superflex: 62 },
    rank: { oneQB: 52, superflex: 56 },
    injuries: [],
    advancedStats: { yprr: 2.43, targetShare: 29.9 },
    cfbdLookup: { team: "LSU", year: 2025 },
  },
  {
    id: 56,
    name: "Zachariah Branch",
    position: "WR",
    college: "Georgia",
    age: 22,
    height: "5-9",
    weight: 175,
    projectedRound: 1,
    projectedPick: 20,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["De'Von Achane", "Percy Harvin"],
    dynastyADP: { oneQB: 8, superflex: 10 },
    rank: { oneQB: 8, superflex: 12 },
    injuries: [],
    advancedStats: { yprr: 2.57, targetShare: 29.4 },
    cfbdLookup: { team: "Georgia", year: 2025 },
  },
  {
    id: 57,
    name: "Malachi Fields",
    position: "WR",
    college: "Notre Dame",
    age: 24,
    height: "6-4",
    weight: 222,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Mike Evans", "Tee Higgins"],
    dynastyADP: { oneQB: 18, superflex: 22 },
    rank: { oneQB: 16, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.2, targetShare: 21.7 },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
  },
  {
    id: 58,
    name: "Chris Bell",
    position: "WR",
    college: "Louisville",
    age: 22,
    height: "6-2",
    weight: 220,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Ricky Pearsall", "Adonai Mitchell"],
    dynastyADP: { oneQB: 18, superflex: 22 },
    rank: { oneQB: 16, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.55, targetShare: 29.4 },
    cfbdLookup: { team: "Louisville", year: 2025 },
  },
  {
    id: 59,
    name: "Antonio Williams",
    position: "WR",
    college: "Clemson",
    age: 22,
    height: "5-11",
    weight: 190,
    projectedRound: 2,
    projectedPick: 50,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["Jayden Reed", "Quentin Johnston"],
    dynastyADP: { oneQB: 18, superflex: 22 },
    rank: { oneQB: 16, superflex: 20 },
    injuries: [],
    advancedStats: { yprr: 2.27, targetShare: 26.8 },
    cfbdLookup: { team: "Clemson", year: 2025 },
  },
  {
    id: 60,
    name: "De'Zhaun Stribling",
    position: "WR",
    college: "Ole Miss",
    age: 23,
    height: "6-2",
    weight: 207,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Ja'Lynn Polk", "Roman Wilson"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.15, targetShare: 19.6 },
    cfbdLookup: { team: "Ole Miss", year: 2025 },
  },
  {
    id: 61,
    name: "Ja'Kobi Lane",
    position: "WR",
    college: "USC",
    age: 21,
    height: "6-4",
    weight: 200,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["George Pickens", "Sidney Rice"],
    dynastyADP: { oneQB: 42, superflex: 46 },
    rank: { oneQB: 38, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: 2.42, targetShare: 23.9 },
    cfbdLookup: { team: "USC", year: 2025 },
  },
  {
    id: 62,
    name: "Jordan Hudson",
    position: "WR",
    college: "SMU",
    age: 22,
    height: "6-1",
    weight: 195,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Darnell Mooney", "Marvin Jones"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 2.16, targetShare: 25.3 },
    cfbdLookup: { team: "SMU", year: 2025 },
  },
  {
    id: 63,
    name: "Devin Voisin",
    position: "WR",
    college: "South Alabama",
    age: 24,
    height: "5-10",
    weight: 182,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Nico Collins", "Tyler Boyd"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 2.38, targetShare: 31.4 },
    cfbdLookup: { team: "South Alabama", year: 2025 },
  },
  {
    id: 64,
    name: "Lewis Bond",
    position: "WR",
    college: "Boston College",
    age: 24,
    height: "6-0",
    weight: 195,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["K.J. Osborn", "Kayshon Boutte"],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 2.09, targetShare: 23.4 },
    cfbdLookup: { team: "Boston College", year: 2025 },
  },
  {
    id: 65,
    name: "RaRa Thomas",
    position: "WR",
    college: "Troy",
    age: 23,
    height: "6-2",
    weight: 210,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Kadarius Toney", "Mecole Hardman"],
    dynastyADP: { oneQB: 58, superflex: 62 },
    rank: { oneQB: 52, superflex: 56 },
    injuries: [],
    advancedStats: { yprr: 1.96, targetShare: 22.9 },
    cfbdLookup: { team: "Troy", year: 2025 },
  },
  {
    id: 66,
    name: "Barion Brown",
    position: "WR",
    college: "LSU",
    age: 22,
    height: "6-1",
    weight: 182,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Devin Hester", "Cordarrelle Patterson"],
    dynastyADP: { oneQB: 52, superflex: 56 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: 1.77, targetShare: 27.6 },
    cfbdLookup: { team: "LSU", year: 2025 },
  },
  {
    id: 67,
    name: "Christian Leary",
    position: "WR",
    college: "Western Michigan",
    age: 23,
    height: "5-10",
    weight: 175,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Rondale Moore", "Kadarius Toney"],
    dynastyADP: { oneQB: 64, superflex: 68 },
    rank: { oneQB: 58, superflex: 62 },
    injuries: [],
    advancedStats: { yprr: 1.95, targetShare: 30.0 },
    cfbdLookup: { team: "Western Michigan", year: 2025 },
  },
  {
    id: 68,
    name: "Germie Bernard",
    position: "WR",
    college: "Alabama",
    age: 22,
    height: "6-1",
    weight: 205,
    projectedRound: 3,
    projectedPick: 85,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Deebo Samuel", "Jarvis Landry"],
    dynastyADP: { oneQB: 30, superflex: 34 },
    rank: { oneQB: 28, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: 1.7, targetShare: 20.1 },
    cfbdLookup: { team: "Alabama", year: 2025 },
  },
  {
    id: 69,
    name: "Caleb Hawkins",
    position: "RB",
    college: "Oklahoma State",
    age: 20,
    height: "6-2",
    weight: 200,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["Derrick Henry", "D'Andre Swift"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "North Texas", year: 2025 },
    stats: { rushingYards: 1431, rushingTDs: 25, yardsPerCarry: 6.2, receptions: 32, receivingYards: 370, receivingTDs: 0, epa: 0.15, pffGrade: 92.6, pffRunGrade: 94.1, elusiveRating: 179.0 },
  },
  {
    id: 70,
    name: "Ahmad Hardy",
    position: "RB",
    college: "Missouri",
    age: 20,
    height: "5-10",
    weight: 210,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["Emmitt Smith", "Mark Ingram"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Missouri", year: 2025 },
    stats: { rushingYards: 1648, rushingTDs: 16, yardsPerCarry: 6.4, receptions: 6, receivingYards: 22, receivingTDs: 0, epa: 0.15, pffGrade: 91.9, pffRunGrade: 92.5, elusiveRating: 178.2 },
  },
  {
    id: 71,
    name: "Jai'Den Thomas",
    position: "RB",
    college: "UNLV",
    age: 21,
    height: "5-10",
    weight: 180,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Raheem Mostert", "Nyheim Hines"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Unlv", year: 2025 },
    stats: { rushingYards: 1036, rushingTDs: 12, yardsPerCarry: 7.0, receptions: 39, receivingYards: 237, receivingTDs: 0, epa: 0.15, pffGrade: 90.7, pffRunGrade: 92.7, elusiveRating: 155.7 },
  },
  {
    id: 72,
    name: "Kentrel Bullock",
    position: "RB",
    college: "South Alabama",
    age: 24,
    height: "5-10",
    weight: 205,
    projectedRound: 6,
    projectedPick: 195,
    projectedTeam: "PIT",
    breakoutAge: 23,
    playerComps: ["Latavius Murray", "Damien Harris"],
    dynastyADP: { oneQB: 45, superflex: 51 },
    rank: { oneQB: 40, superflex: 42 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "South Alabama", year: 2025 },
    stats: { rushingYards: 1082, rushingTDs: 14, yardsPerCarry: 5.0, receptions: 14, receivingYards: 66, receivingTDs: 0, epa: 0.15, pffGrade: 90.3, pffRunGrade: 90.4, elusiveRating: 72.2 },
  },
  {
    id: 73,
    name: "Nate Frazier",
    position: "RB",
    college: "Georgia",
    age: 20,
    height: "5-10",
    weight: 210,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["Chris Johnson", "Nick Chubb"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Georgia", year: 2025 },
    stats: { rushingYards: 947, rushingTDs: 6, yardsPerCarry: 5.5, receptions: 16, receivingYards: 116, receivingTDs: 0, epa: 0.15, pffGrade: 90.0, pffRunGrade: 90.8, elusiveRating: 74.6 },
  },
  {
    id: 74,
    name: "Kaytron Allen",
    position: "RB",
    college: "Penn State",
    age: 23,
    height: "5-11",
    weight: 216,
    projectedRound: 3,
    projectedPick: 85,
    projectedTeam: "KC",
    breakoutAge: 18,
    playerComps: ["David Montgomery", "Ezekiel Elliott"],
    dynastyADP: { oneQB: 14, superflex: 21 },
    rank: { oneQB: 12, superflex: 19 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Penn State", year: 2025 },
    stats: { rushingYards: 1303, rushingTDs: 15, yardsPerCarry: 6.2, receptions: 18, receivingYards: 68, receivingTDs: 0, epa: 0.15, pffGrade: 89.5, pffRunGrade: 91.3, elusiveRating: 102.6 },
  },
  {
    id: 75,
    name: "Nate Sheppard",
    position: "RB",
    college: "Duke",
    age: 20,
    height: "5-10",
    weight: 197,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["Alvin Kamara", "Devonta Freeman"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Duke", year: 2025 },
    stats: { rushingYards: 1132, rushingTDs: 11, yardsPerCarry: 5.7, receptions: 37, receivingYards: 286, receivingTDs: 0, epa: 0.15, pffGrade: 89.5, pffRunGrade: 90.9, elusiveRating: 115.5 },
  },
  {
    id: 76,
    name: "Jordon Davison",
    position: "RB",
    college: "Oregon",
    age: 20,
    height: "6-0",
    weight: 215,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["Josh Jacobs", "Jonathan Taylor"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Oregon", year: 2025 },
    stats: { rushingYards: 665, rushingTDs: 15, yardsPerCarry: 5.9, receptions: 12, receivingYards: 62, receivingTDs: 0, epa: 0.15, pffGrade: 89.1, pffRunGrade: 91.4, elusiveRating: 53.2 },
  },
  {
    id: 77,
    name: "Antwan Raymond",
    position: "RB",
    college: "Rutgers",
    age: 21,
    height: "5-11",
    weight: 205,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Marshawn Lynch", "Kareem Hunt"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Rutgers", year: 2025 },
    stats: { rushingYards: 1238, rushingTDs: 13, yardsPerCarry: 5.1, receptions: 18, receivingYards: 224, receivingTDs: 0, epa: 0.15, pffGrade: 89.0, pffRunGrade: 87.8, elusiveRating: 116.2 },
  },
  {
    id: 78,
    name: "J'Koby Williams",
    position: "RB",
    college: "Texas Tech",
    age: 21,
    height: "5-10",
    weight: 185,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Tarik Cohen", "Jamaal Charles"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Texas Tech", year: 2025 },
    stats: { rushingYards: 859, rushingTDs: 6, yardsPerCarry: 5.5, receptions: 35, receivingYards: 388, receivingTDs: 0, epa: 0.15, pffGrade: 88.4, pffRunGrade: 87.9, elusiveRating: 139.9 },
  },
  {
    id: 79,
    name: "Jordan Marshall",
    position: "RB",
    college: "Michigan",
    age: 20,
    height: "5-11",
    weight: 216,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["David Montgomery", "Zack Moss"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Michigan", year: 2025 },
    stats: { rushingYards: 932, rushingTDs: 10, yardsPerCarry: 6.2, receptions: 9, receivingYards: 92, receivingTDs: 0, epa: 0.15, pffGrade: 87.8, pffRunGrade: 88.6, elusiveRating: 91.4 },
  },
  {
    id: 80,
    name: "Jadan Baugh",
    position: "RB",
    college: "Florida",
    age: 21,
    height: "6-1",
    weight: 231,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["Josh Jacobs", "Derrick Henry"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Florida", year: 2025 },
    stats: { rushingYards: 1168, rushingTDs: 8, yardsPerCarry: 5.3, receptions: 33, receivingYards: 210, receivingTDs: 0, epa: 0.15, pffGrade: 87.7, pffRunGrade: 89.5, elusiveRating: 103.8 },
  },
  {
    id: 81,
    name: "Braylon McReynolds",
    position: "RB",
    college: "Louisiana-Monroe",
    age: 23,
    height: "5-7",
    weight: 195,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Nyheim Hines", "Darren Sproles"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Louisiana-Monroe", year: 2025 },
    stats: { rushingYards: 658, rushingTDs: 3, yardsPerCarry: 5.3, receptions: 14, receivingYards: 66, receivingTDs: 0, epa: 0.15, pffGrade: 87.6, pffRunGrade: 85.1, elusiveRating: 153.5 },
  },
  {
    id: 82,
    name: "Bo Jackson",
    position: "RB",
    college: "Ohio State",
    age: 20,
    height: "6-0",
    weight: 217,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["Saquon Barkley", "TreVeyon Henderson"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Ohio State", year: 2025 },
    stats: { rushingYards: 1085, rushingTDs: 6, yardsPerCarry: 6.1, receptions: 19, receivingYards: 200, receivingTDs: 0, epa: 0.15, pffGrade: 87.1, pffRunGrade: 86.4, elusiveRating: 78.5 },
  },
  {
    id: 83,
    name: "Kewan Lacy",
    position: "RB",
    college: "Ole Miss",
    age: 20,
    height: "5-11",
    weight: 200,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["Aaron Jones", "Dalvin Cook"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Ole Miss", year: 2025 },
    stats: { rushingYards: 1564, rushingTDs: 24, yardsPerCarry: 5.1, receptions: 29, receivingYards: 177, receivingTDs: 0, epa: 0.15, pffGrade: 86.9, pffRunGrade: 91.6, elusiveRating: 97.9 },
  },
  {
    id: 84,
    name: "Keyjuan Brown",
    position: "RB",
    college: "Louisville",
    age: 22,
    height: "5-10",
    weight: 210,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Damien Harris", "Rex Burkhead"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Louisville", year: 2025 },
    stats: { rushingYards: 703, rushingTDs: 6, yardsPerCarry: 7.3, receptions: 12, receivingYards: 118, receivingTDs: 0, epa: 0.15, pffGrade: 86.8, pffRunGrade: 91.5, elusiveRating: 171.2 },
  },
  {
    id: 85,
    name: "Mark Fletcher Jr.",
    position: "RB",
    college: "Miami",
    age: 21,
    height: "6-2",
    weight: 225,
    projectedRound: 4,
    projectedPick: 120,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Najee Harris", "Leonard Fournette"],
    dynastyADP: { oneQB: 28, superflex: 34 },
    rank: { oneQB: 26, superflex: 30 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Miami", year: 2025 },
    stats: { rushingYards: 1184, rushingTDs: 12, yardsPerCarry: 5.5, receptions: 17, receivingYards: 140, receivingTDs: 0, epa: 0.15, pffGrade: 86.7, pffRunGrade: 92.0, elusiveRating: 102.8 },
  },
  {
    id: 86,
    name: "DeSean Bishop",
    position: "RB",
    college: "Tennessee",
    age: 21,
    height: "5-10",
    weight: 208,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Dameon Pierce", "Phillip Lindsay"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Tennessee", year: 2025 },
    stats: { rushingYards: 1076, rushingTDs: 16, yardsPerCarry: 5.9, receptions: 15, receivingYards: 135, receivingTDs: 0, epa: 0.15, pffGrade: 86.7, pffRunGrade: 90.1, elusiveRating: 65.2 },
  },
  {
    id: 87,
    name: "Cam Edwards",
    position: "RB",
    college: "UConn",
    age: 23,
    height: "5-11",
    weight: 210,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["James Conner", "Gus Edwards"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Uconn", year: 2025 },
    stats: { rushingYards: 1226, rushingTDs: 15, yardsPerCarry: 5.9, receptions: 19, receivingYards: 187, receivingTDs: 0, epa: 0.15, pffGrade: 86.4, pffRunGrade: 87.4, elusiveRating: 83.9 },
  },
  {
    id: 88,
    name: "Greg Burrell",
    position: "RB",
    college: "Texas State",
    age: 21,
    height: "6-1",
    weight: 205,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Khalil Herbert", "Cordarrelle Patterson"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Texas State", year: 2025 },
    stats: { rushingYards: 671, rushingTDs: 3, yardsPerCarry: 6.7, receptions: 12, receivingYards: 115, receivingTDs: 0, epa: 0.15, pffGrade: 86.3, pffRunGrade: 88.9, elusiveRating: 151.7 },
  },
  {
    id: 89,
    name: "LJ Martin",
    position: "RB",
    college: "BYU",
    age: 22,
    height: "6-2",
    weight: 220,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["Tyler Allgeier", "AJ Dillon"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Byu", year: 2025 },
    stats: { rushingYards: 1299, rushingTDs: 12, yardsPerCarry: 5.5, receptions: 36, receivingYards: 251, receivingTDs: 0, epa: 0.15, pffGrade: 86.2, pffRunGrade: 87.9, elusiveRating: 86.3 },
  },
  {
    id: 90,
    name: "Sire Gaines",
    position: "RB",
    college: "Boise State",
    age: 20,
    height: "6-0",
    weight: 209,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["George Holani", "Ashton Jeanty"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Boise State", year: 2025 },
    stats: { rushingYards: 812, rushingTDs: 8, yardsPerCarry: 5.0, receptions: 11, receivingYards: 72, receivingTDs: 0, epa: 0.15, pffGrade: 86.2, pffRunGrade: 88.9, elusiveRating: 98.1 },
  },
  {
    id: 91,
    name: "OJ Arnold",
    position: "RB",
    college: "Georgia Southern",
    age: 23,
    height: "5-9",
    weight: 195,
    projectedRound: 7,
    projectedPick: 230,
    projectedTeam: "ATL",
    breakoutAge: 21,
    playerComps: ["D'Onta Foreman", "Cordarrelle Patterson"],
    dynastyADP: { oneQB: 58, superflex: 65 },
    rank: { oneQB: 50, superflex: 52 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Georgia Southern", year: 2025 },
    stats: { rushingYards: 1026, rushingTDs: 5, yardsPerCarry: 7.1, receptions: 20, receivingYards: 207, receivingTDs: 0, epa: 0.15, pffGrade: 86.1, pffRunGrade: 89.2, elusiveRating: 67.8 },
  },
  {
    id: 92,
    name: "Marcellous Hawkins",
    position: "RB",
    college: "Virginia Tech",
    age: 24,
    height: "5-11",
    weight: 219,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Bhayshul Tuten", "Phillip Lindsay"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Virginia Tech", year: 2025 },
    stats: { rushingYards: 744, rushingTDs: 1, yardsPerCarry: 6.3, receptions: 11, receivingYards: 79, receivingTDs: 0, epa: 0.15, pffGrade: 86.0, pffRunGrade: 90.9, elusiveRating: 170.7 },
  },
  {
    id: 93,
    name: "Adam Mohammed",
    position: "RB",
    college: "Washington",
    age: 22,
    height: "6-0",
    weight: 220,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Damien Harris", "Sony Michel"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Washington", year: 2025 },
    stats: { rushingYards: 523, rushingTDs: 5, yardsPerCarry: 4.9, receptions: 17, receivingYards: 138, receivingTDs: 0, epa: 0.15, pffGrade: 85.9, pffRunGrade: 89.5, elusiveRating: 136.3 },
  },
  {
    id: 94,
    name: "Trequan Jones",
    position: "RB",
    college: "Old Dominion",
    age: 24,
    height: "5-9",
    weight: 183,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Raheem Mostert", "De'Von Achane"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Dominion", year: 2025 },
    stats: { rushingYards: 777, rushingTDs: 6, yardsPerCarry: 7.5, receptions: 6, receivingYards: 20, receivingTDs: 0, epa: 0.15, pffGrade: 85.9, pffRunGrade: 86.8, elusiveRating: 81.7 },
  },
  {
    id: 95,
    name: "Cam Cook",
    position: "RB",
    college: "Jacksonville State",
    age: 22,
    height: "5-11",
    weight: 200,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Ke'Shawn Vaughn", "Dameon Pierce"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Jacksonville State", year: 2025 },
    stats: { rushingYards: 1650, rushingTDs: 16, yardsPerCarry: 5.6, receptions: 30, receivingYards: 291, receivingTDs: 0, epa: 0.15, pffGrade: 85.8, pffRunGrade: 89.3, elusiveRating: 135.8 },
  },
  {
    id: 96,
    name: "Lucky Sutton",
    position: "RB",
    college: "San Diego State",
    age: 22,
    height: "6-1",
    weight: 225,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Le'Veon Bell", "Rashad Penny"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "San Diego State", year: 2025 },
    stats: { rushingYards: 1297, rushingTDs: 10, yardsPerCarry: 5.1, receptions: 6, receivingYards: 6, receivingTDs: 0, epa: 0.15, pffGrade: 85.1, pffRunGrade: 88.6, elusiveRating: 74.3 },
  },
  {
    id: 97,
    name: "Will Henderson III",
    position: "RB",
    college: "UTSA",
    age: 20,
    height: "5-10",
    weight: 185,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 19,
    playerComps: ["De'Von Achane", "Tyreek Hill"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Utsa", year: 2025 },
    stats: { rushingYards: 862, rushingTDs: 6, yardsPerCarry: 6.9, receptions: 19, receivingYards: 132, receivingTDs: 0, epa: 0.15, pffGrade: 85.1, pffRunGrade: 89.0, elusiveRating: 92.3 },
  },
  {
    id: 98,
    name: "Tawee Walker",
    position: "RB",
    college: "Cincinnati",
    age: 25,
    height: "5-9",
    weight: 218,
    projectedRound: 7,
    projectedPick: 240,
    projectedTeam: "DEN",
    breakoutAge: 23,
    playerComps: ["Zack Moss", "Jeremy Hill"],
    dynastyADP: { oneQB: 60, superflex: 68 },
    rank: { oneQB: 52, superflex: 55 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Cincinnati", year: 2025 },
    stats: { rushingYards: 714, rushingTDs: 4, yardsPerCarry: 6.0, receptions: 18, receivingYards: 77, receivingTDs: 0, epa: 0.15, pffGrade: 85.0, pffRunGrade: 88.2, elusiveRating: 91.6 },
  },
  {
    id: 97,
    name: "Le'Veon Moss",
    position: "RB",
    college: "Texas A&M",
    age: 23,
    height: "5-11",
    weight: 210,
    projectedRound: 5,
    projectedPick: 160,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Rhamondre Stevenson", "Zamir White"],
    dynastyADP: { oneQB: 36, superflex: 42 },
    rank: { oneQB: 34, superflex: 38 },
    injuries: [{ type: "ACL/MCL", date: "2024-10", severity: "Severe", gamesOut: 6 }, { type: "Ankle", date: "2025-09", severity: "Moderate", gamesOut: 5 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Texas A&M", year: 2025 },
    stats: { rushingYards: 404, rushingTDs: 6, yardsPerCarry: 5.2, receptions: 2, receivingYards: 3, receivingTDs: 0, epa: 0.10, pffGrade: 72.0, pffRunGrade: 74.0, elusiveRating: 65.8 },
  },
  {
    id: 98,
    name: "Adam Randall",
    position: "RB",
    college: "Clemson",
    age: 22,
    height: "6-3",
    weight: 232,
    projectedRound: 5,
    projectedPick: 165,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Cordarrelle Patterson", "AJ Dillon"],
    dynastyADP: { oneQB: 38, superflex: 44 },
    rank: { oneQB: 36, superflex: 40 },
    injuries: [{ type: "ACL", date: "2022-04", severity: "Severe", gamesOut: 8 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Clemson", year: 2025 },
    stats: { rushingYards: 814, rushingTDs: 10, yardsPerCarry: 4.8, receptions: 36, receivingYards: 254, receivingTDs: 3, epa: 0.12, pffGrade: 68.0, pffRunGrade: 70.0, elusiveRating: 75.0 },
  },
  {
    id: 99,
    name: "Dean Connors",
    position: "RB",
    college: "Houston",
    age: 23,
    height: "6-0",
    weight: 206,
    projectedRound: 7,
    projectedPick: 235,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Nyheim Hines", "J.D. McKissic"],
    dynastyADP: { oneQB: 55, superflex: 62 },
    rank: { oneQB: 48, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Houston", year: 2025 },
    stats: { rushingYards: 800, rushingTDs: 6, yardsPerCarry: 4.5, receptions: 28, receivingYards: 220, receivingTDs: 3, epa: 0.10, pffGrade: 70.0, pffRunGrade: 72.0, elusiveRating: 68.0 },
  },
  {
    id: 100,
    name: "Sone Ntoh",
    position: "RB",
    college: "Monmouth",
    age: 24,
    height: "5-11",
    weight: 235,
    projectedRound: 7,
    projectedPick: 250,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["LeGarrette Blount", "Derrick Gore"],
    dynastyADP: { oneQB: 58, superflex: 64 },
    rank: { oneQB: 50, superflex: 54 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Monmouth", year: 2024 },
    stats: { rushingYards: 487, rushingTDs: 25, yardsPerCarry: 4.5, receptions: 5, receivingYards: 30, receivingTDs: 0, epa: 0.10, pffGrade: 72.0, pffRunGrade: 74.0, elusiveRating: 65.0 },
  },
  {
    id: 101,
    name: "CJ Donaldson",
    position: "RB",
    college: "Ohio State",
    age: 23,
    height: "6-2",
    weight: 234,
    projectedRound: 6,
    projectedPick: 200,
    projectedTeam: null,
    breakoutAge: 18,
    playerComps: ["LeGarrette Blount", "Derrick Gore"],
    dynastyADP: { oneQB: 46, superflex: 52 },
    rank: { oneQB: 40, superflex: 44 },
    injuries: [{ type: "Various", date: "2024-09", severity: "Moderate", gamesOut: 4 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Ohio State", year: 2025 },
    stats: { rushingYards: 361, rushingTDs: 10, yardsPerCarry: 3.8, receptions: 15, receivingYards: 96, receivingTDs: 0, epa: 0.10, pffGrade: 71.5, pffRunGrade: 71.5, elusiveRating: 60.0 },
  },
  {
    id: 102,
    name: "Hollywood Smothers",
    position: "RB",
    college: "NC State",
    age: 21,
    height: "5-11",
    weight: 195,
    projectedRound: null,
    projectedPick: null,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Jaylen Warren", "Samaje Perine"],
    dynastyADP: { oneQB: null, superflex: null },
    rank: { oneQB: null, superflex: null },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "NC State", year: 2025 },
    stats: { rushingYards: 939, rushingTDs: 6, yardsPerCarry: 5.9, receptions: 37, receivingYards: 189, receivingTDs: 2, epa: 0.12, pffGrade: 76.0, pffRunGrade: 78.0, elusiveRating: 85.0 },
  },
  {
    id: 103,
    name: "Dylan Devezin",
    position: "RB",
    college: "Notre Dame",
    age: 22,
    height: "6-2",
    weight: 216,
    projectedRound: 7,
    projectedPick: 255,
    projectedTeam: null,
    breakoutAge: null,
    playerComps: [],
    dynastyADP: { oneQB: 62, superflex: 68 },
    rank: { oneQB: 54, superflex: 58 },
    injuries: [{ type: "Shoulder", date: "2025-08", severity: "Severe", gamesOut: 14 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Notre Dame", year: 2025 },
    stats: { rushingYards: 0, rushingTDs: 0, yardsPerCarry: 0, receptions: 0, receivingYards: 0, receivingTDs: 0, epa: null, pffGrade: null, pffRunGrade: null, elusiveRating: null },
  },
  {
    id: 104,
    name: "Kejon Owens",
    position: "RB",
    college: "Florida International",
    age: 24,
    height: "5-10",
    weight: 210,
    projectedRound: 6,
    projectedPick: 210,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Damien Harris", "Sony Michel"],
    dynastyADP: { oneQB: 50, superflex: 56 },
    rank: { oneQB: 44, superflex: 48 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Florida International", year: 2025 },
    stats: { rushingYards: 1334, rushingTDs: 11, yardsPerCarry: 6.3, receptions: 15, receivingYards: 120, receivingTDs: 1, epa: 0.14, pffGrade: 81.4, pffRunGrade: 83.3, elusiveRating: 85.0 },
  },
  {
    id: 105,
    name: "Rahsul Faison",
    position: "RB",
    college: "South Carolina",
    age: 26,
    height: "5-11",
    weight: 219,
    projectedRound: 5,
    projectedPick: 175,
    projectedTeam: null,
    breakoutAge: 24,
    playerComps: ["Carlos Hyde", "Mike Davis"],
    dynastyADP: { oneQB: 44, superflex: 50 },
    rank: { oneQB: 40, superflex: 44 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "South Carolina", year: 2025 },
    stats: { rushingYards: 470, rushingTDs: 3, yardsPerCarry: 4.9, receptions: 19, receivingYards: 118, receivingTDs: 0, epa: 0.10, pffGrade: 75.0, pffRunGrade: 78.0, elusiveRating: 72.0 },
  },
  {
    id: 106,
    name: "Desmond Reid",
    position: "RB",
    college: "Pittsburgh",
    age: 22,
    height: "5-8",
    weight: 175,
    projectedRound: 6,
    projectedPick: 195,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["De'Von Achane", "Bucky Irving"],
    dynastyADP: { oneQB: 20, superflex: 26 },
    rank: { oneQB: 18, superflex: 22 },
    injuries: [{ type: "Undisclosed", date: "2025-09", severity: "Moderate", gamesOut: 5 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Pittsburgh", year: 2025 },
    stats: { rushingYards: 278, rushingTDs: 2, yardsPerCarry: 4.6, receptions: 23, receivingYards: 317, receivingTDs: 2, epa: 0.14, pffGrade: 82.0, pffRunGrade: 80.0, elusiveRating: 95.0 },
  },
  {
    id: 107,
    name: "Anthony Hankerson",
    position: "RB",
    college: "Oregon State",
    age: 23,
    height: "5-8",
    weight: 203,
    projectedRound: 7,
    projectedPick: 240,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Dameon Pierce", "Dare Ogunbowale"],
    dynastyADP: { oneQB: 52, superflex: 58 },
    rank: { oneQB: 46, superflex: 50 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Oregon State", year: 2025 },
    stats: { rushingYards: 1090, rushingTDs: 9, yardsPerCarry: 4.7, receptions: 12, receivingYards: 80, receivingTDs: 0, epa: 0.11, pffGrade: 73.7, pffRunGrade: 76.1, elusiveRating: 75.0 },
  },
  {
    id: 108,
    name: "Davon Booth",
    position: "RB",
    college: "Mississippi State",
    age: 23,
    height: "5-9",
    weight: 205,
    projectedRound: 7,
    projectedPick: 245,
    projectedTeam: null,
    breakoutAge: 22,
    playerComps: ["Gio Bernard", "Ty Montgomery"],
    dynastyADP: { oneQB: 56, superflex: 63 },
    rank: { oneQB: 48, superflex: 52 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Mississippi State", year: 2025 },
    stats: { rushingYards: 553, rushingTDs: 7, yardsPerCarry: 4.1, receptions: 15, receivingYards: 165, receivingTDs: 2, epa: 0.09, pffGrade: 70.0, pffRunGrade: 72.0, elusiveRating: 65.0 },
  },
  {
    id: 109,
    name: "Demond Claiborne",
    position: "RB",
    college: "Wake Forest",
    age: 22,
    height: "5-10",
    weight: 188,
    projectedRound: 4,
    projectedPick: 115,
    projectedTeam: null,
    breakoutAge: 21,
    playerComps: ["Raheem Mostert", "Keaton Mitchell"],
    dynastyADP: { oneQB: 30, superflex: 36 },
    rank: { oneQB: 28, superflex: 32 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Wake Forest", year: 2025 },
    stats: { rushingYards: 907, rushingTDs: 10, yardsPerCarry: 5.1, receptions: 26, receivingYards: 130, receivingTDs: 0, epa: 0.14, pffGrade: 68.6, pffRunGrade: 76.8, elusiveRating: 90.0 },
  },
  {
    id: 110,
    name: "J'Mari Taylor",
    position: "RB",
    college: "Virginia",
    age: 24,
    height: "5-9",
    weight: 205,
    projectedRound: 6,
    projectedPick: 210,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Ronnie Hillman", "Malik Davis"],
    dynastyADP: { oneQB: 48, superflex: 54 },
    rank: { oneQB: 42, superflex: 46 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Virginia", year: 2025 },
    stats: { rushingYards: 1062, rushingTDs: 14, yardsPerCarry: 4.8, receptions: 43, receivingYards: 253, receivingTDs: 1, epa: 0.13, pffGrade: 76.8, pffRunGrade: 79.2, elusiveRating: 78.0 },
  },
  {
    id: 111,
    name: "Lincoln Pare",
    position: "RB",
    college: "Texas State",
    age: 24,
    height: "5-8",
    weight: 196,
    projectedRound: 7,
    projectedPick: 245,
    projectedTeam: null,
    breakoutAge: 23,
    playerComps: ["Rex Burkhead", "Ty Johnson"],
    dynastyADP: { oneQB: 54, superflex: 60 },
    rank: { oneQB: 47, superflex: 51 },
    injuries: [],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Texas State", year: 2025 },
    stats: { rushingYards: 1128, rushingTDs: 12, yardsPerCarry: 5.4, receptions: 37, receivingYards: 312, receivingTDs: 2, epa: 0.13, pffGrade: 76.0, pffRunGrade: 78.0, elusiveRating: 80.0 },
  },
  {
    id: 112,
    name: "Jam Miller",
    position: "RB",
    college: "Alabama",
    age: 22,
    height: "5-10",
    weight: 221,
    projectedRound: 5,
    projectedPick: 170,
    projectedTeam: null,
    breakoutAge: 20,
    playerComps: ["Isiah Pacheco", "Corey Clement"],
    dynastyADP: { oneQB: 36, superflex: 42 },
    rank: { oneQB: 32, superflex: 36 },
    injuries: [{ type: "Upper Body", date: "2025-08", severity: "Moderate", gamesOut: 3 }],
    advancedStats: { yprr: null, targetShare: null },
    cfbdLookup: { team: "Alabama", year: 2025 },
    stats: { rushingYards: 504, rushingTDs: 3, yardsPerCarry: 3.9, receptions: 19, receivingYards: 109, receivingTDs: 0, epa: 0.10, pffGrade: 74.0, pffRunGrade: 76.0, elusiveRating: 72.0 },
  },
];

// Merge receiving perspective data into each prospect
const prospects2026 = prospects2026Raw.map(p => ({
  ...p,
  receivingByPerspective: getReceivingData(p.name),
}));

export const getProspects = () => prospects2026;
export const getProspectByName = (name) =>
  prospects2026.find((p) => p.name.toLowerCase() === name.toLowerCase());
export const getProspectById = (id) => prospects2026.find((p) => p.id === id);

export default prospects2026;
